#!/usr/bin/env python3
"""Generate deterministic temporary lessons for continuous-reader testing."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from scripts import learn_glossary
except ModuleNotFoundError:  # Direct execution from the scripts directory.
    import learn_glossary  # type: ignore[no-redef]


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
TEST_ROOT = REPOSITORY_ROOT / "site" / "learn" / "scrolling-test"
GENERATED_MARKER = (
    "<!-- Generated by scripts/generate_scrolling_test_lessons.py; do not edit. -->"
)
LESSONS_PER_TRACK = 10
DIFFICULTY_CYCLE = (
    "Beginner",
    "Intermediate",
    "Advanced",
    "Beginner",
    "Intermediate",
    "Advanced",
    "Beginner",
    "Intermediate",
    "Advanced",
    "Beginner",
)
WARNING_TEXT = (
    "Temporary scrolling test content. "
    "This page is not part of the finished curriculum."
)


class FixtureValidationError(RuntimeError):
    """Raised when scrolling fixtures are unsafe, missing, or stale."""


@dataclass(frozen=True)
class GenerationResult:
    created: int = 0
    unchanged: int = 0
    invalid: int = 0
    removed: int = 0


def discover_curriculum_inputs() -> tuple[
    list[dict[str, object]], list[dict[str, object]]
]:
    """Use the canonical Learn parser while excluding only generated fixtures."""
    tracks = learn_glossary.discover_tracks()
    real_lessons = learn_glossary.discover_lessons(
        include_scrolling_tests=False
    )
    learn_glossary.build_curriculum(tracks, real_lessons)
    return tracks, real_lessons


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def metadata_tag(
    track: dict[str, object],
    real_lessons: list[dict[str, object]],
) -> str:
    track_lessons = [
        lesson
        for lesson in real_lessons
        if lesson["track_id"] == track["id"]
    ]
    for lesson in sorted(track_lessons, key=lambda item: int(item["order"])):
        for tag in lesson["tags"]:
            if str(tag) in learn_glossary.TRACKS:
                return str(tag)
    title = str(track["title"]).casefold()
    for tag in learn_glossary.TRACKS:
        if str(tag).casefold() in title:
            return str(tag)
    return str(learn_glossary.TRACKS[0])


def canonical_fixture_term() -> str:
    entries = learn_glossary.validate_public_data(
        learn_glossary.read_json(learn_glossary.PUBLIC_DATA_PATH)
    )
    slugs = {str(entry["slug"]) for entry in entries}
    return "backgammon" if "backgammon" in slugs else sorted(slugs)[0]


def lesson_content(
    *,
    track: dict[str, object],
    lesson_number: int,
    lesson_order: int,
    tag: str,
    term: str,
    same_track_route: str,
    next_track_route: str | None,
) -> str:
    track_title = str(track["title"])
    title = f"Scrolling Test: {track_title} {lesson_number:02d}"
    description = (
        f"Deterministic continuous-scrolling fixture {lesson_number:02d} "
        f"for {track_title}."
    )
    difficulty = DIFFICULTY_CYCLE[lesson_number - 1]
    cross_track_link = (
        "\n"
        f"[Continue to the next test track]({next_track_route}).\n"
        if next_track_route
        else ""
    )
    return f"""---
title: {yaml_string(title)}
description: {yaml_string(description)}
sidebar: learn
learn-track: {track["id"]}
learn-order: {lesson_order}
categories:
  - {difficulty}
tags:
  - {yaml_string(tag)}
terms:
  - {term}
body-classes: bms-learn-article
toc: true
toc-depth: 3
---

{GENERATED_MARKER}

**{WARNING_TEXT}**

[Jump to Example](#example).

## Overview

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.

Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui, et malesuada magna mollis euismod.

::: {{.column-margin}}
Temporary margin note for {track_title} lesson {lesson_number:02d}.
:::

## Example

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas faucibus mollis interdum, et posuere consectetur est at lobortis.

Vestibulum id ligula porta felis euismod semper. Cras mattis consectetur purus sit amet fermentum.

### Scenario

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lacinia bibendum nulla sed consectetur.

Nullam quis risus eget urna mollis ornare vel eu leo. Curabitur blandit tempus porttitor.

::: {{.callout-note}}
This deterministic callout exists to exercise appended lesson layout.
:::

## Details

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod.

Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Sed posuere consectetur est at lobortis.

### Notes

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla.

Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.

<details>
<summary>Temporary details</summary>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. This native disclosure tests appended interactions.</p>
</details>

## Summary

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.

Donec id elit non mi porta gravida at eget metus. Cum sociis natoque penatibus et magnis dis parturient montes.

[Open another test lesson in this track]({same_track_route}).
{cross_track_link}"""


def build_expected_outputs(
    test_root: Path = TEST_ROOT,
) -> dict[Path, str]:
    tracks, real_lessons = discover_curriculum_inputs()
    term = canonical_fixture_term()
    max_order_by_track = {
        str(track["id"]): max(
            (
                int(lesson["order"])
                for lesson in real_lessons
                if lesson["track_id"] == track["id"]
            ),
            default=0,
        )
        for track in tracks
    }
    outputs: dict[Path, str] = {}
    for track_index, track in enumerate(tracks):
        track_id = str(track["id"])
        tag = metadata_tag(track, real_lessons)
        next_track_route = (
            "/learn/scrolling-test/"
            + str(tracks[track_index + 1]["id"])
            + "/lesson-01.html"
            if track_index + 1 < len(tracks)
            else None
        )
        for lesson_number in range(1, LESSONS_PER_TRACK + 1):
            same_track_number = (
                lesson_number + 1
                if lesson_number < LESSONS_PER_TRACK
                else 1
            )
            path = (
                test_root
                / track_id
                / f"lesson-{lesson_number:02d}.qmd"
            )
            outputs[path] = lesson_content(
                track=track,
                lesson_number=lesson_number,
                lesson_order=max_order_by_track[track_id] + lesson_number,
                tag=tag,
                term=term,
                same_track_route=(
                    f"/learn/scrolling-test/{track_id}/"
                    f"lesson-{same_track_number:02d}.html"
                ),
                next_track_route=next_track_route,
            )
    return outputs


def generated_paths(test_root: Path) -> list[Path]:
    if not test_root.exists():
        return []
    return sorted(test_root.rglob("*.qmd"))


def is_generated_fixture(path: Path) -> bool:
    try:
        return GENERATED_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def remove_empty_directories(test_root: Path) -> None:
    if not test_root.exists():
        return
    for path in sorted(
        (item for item in test_root.rglob("*") if item.is_dir()),
        key=lambda item: len(item.parts),
        reverse=True,
    ):
        if not any(path.iterdir()):
            path.rmdir()
    if test_root.exists() and not any(test_root.iterdir()):
        test_root.rmdir()


def generate(test_root: Path = TEST_ROOT) -> GenerationResult:
    expected = build_expected_outputs(test_root)
    created = unchanged = invalid = removed = 0
    expected_paths = set(expected)

    for path, content in expected.items():
        if path.exists():
            current = path.read_text(encoding="utf-8")
            if current == content:
                unchanged += 1
                continue
            if not is_generated_fixture(path):
                raise FixtureValidationError(
                    f"Refusing to overwrite non-generated fixture path: {path}"
                )
            invalid += 1
        else:
            created += 1
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")

    for path in generated_paths(test_root):
        if path in expected_paths:
            continue
        if is_generated_fixture(path):
            path.unlink()
            removed += 1
    remove_empty_directories(test_root)
    return GenerationResult(created, unchanged, invalid, removed)


def validate(test_root: Path = TEST_ROOT) -> GenerationResult:
    expected = build_expected_outputs(test_root)
    actual_paths = set(generated_paths(test_root))
    expected_paths = set(expected)
    missing = sorted(expected_paths - actual_paths)
    extra = sorted(actual_paths - expected_paths)
    modified = sorted(
        path
        for path in expected_paths & actual_paths
        if path.read_text(encoding="utf-8") != expected[path]
    )
    if missing or extra or modified:
        details = []
        if missing:
            details.append(f"missing={len(missing)}")
        if extra:
            details.append(f"extra={len(extra)}")
        if modified:
            details.append(f"modified={len(modified)}")
        raise FixtureValidationError(
            "Scrolling test lesson validation failed: " + ", ".join(details)
        )

    tracks, _real_lessons = discover_curriculum_inputs()
    for track in tracks:
        track_root = test_root / str(track["id"])
        count = len(list(track_root.glob("lesson-*.qmd")))
        if count != LESSONS_PER_TRACK:
            raise FixtureValidationError(
                f"Track {track['id']} has {count} fixtures; "
                f"expected {LESSONS_PER_TRACK}"
            )
    return GenerationResult(0, len(expected), 0, 0)


def clean(test_root: Path = TEST_ROOT) -> GenerationResult:
    removed = 0
    invalid = 0
    for path in generated_paths(test_root):
        if is_generated_fixture(path):
            path.unlink()
            removed += 1
        else:
            invalid += 1
    remove_empty_directories(test_root)
    return GenerationResult(0, 0, invalid, removed)


def print_summary(command: str, result: GenerationResult) -> None:
    print(
        f"Scrolling test lessons {command}: "
        f"created={result.created}, unchanged={result.unchanged}, "
        f"invalid={result.invalid}, removed={result.removed}"
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("generate", "validate", "clean"))
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        result = {
            "generate": generate,
            "validate": validate,
            "clean": clean,
        }[args.command]()
    except (
        FixtureValidationError,
        learn_glossary.ValidationError,
        OSError,
    ) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print_summary(args.command, result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
