#!/usr/bin/env python3
"""Import, validate, and generate the Learn glossary from public-safe data."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from collections import defaultdict
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import quote, unquote, urljoin, urlsplit


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SITE_ROOT = REPOSITORY_ROOT / "site"
LEARN_ROOT = SITE_ROOT / "learn"
RESEARCH_ROOT = SITE_ROOT / "research"
GLOSSARY_ROOT = LEARN_ROOT / "glossary"
PUBLIC_DATA_PATH = SITE_ROOT / "data" / "glossary.json"
AUTHORING_TERMS_PATH = REPOSITORY_ROOT / "docs" / "learn-glossary-terms.md"
GENERATED_ENTRIES_PATH = GLOSSARY_ROOT / "_entries.html"
GENERATED_ROUTES_PATH = GLOSSARY_ROOT / "_generated-routes.json"

SAFE_INPUT_SHA256 = "ce10ecccc983ab87b7a43bfb46a04e91b44a00d93ba9ee86765638be991595e4"
EXPECTED_SOURCE_ENTRIES = 805
EXPECTED_CANONICAL_ENTRIES = 624
EXPECTED_ALIAS_ENTRIES = 181

DIFFICULTIES = ("Beginner", "Intermediate", "Advanced")
TRACKS = (
    "Doubling Cube",
    "Checker Play",
    "Opening Play",
    "Match Play",
    "Endgames",
    "Engines and Analysis",
)

FORBIDDEN_KEYS = {
    "source_ids",
    "sources",
    "source_url",
    "editorial_status",
    "rewrite_summary",
    "copyright_note",
}
FORBIDDEN_TEXT_PATTERNS = {
    "source_ids": re.compile(r"\bsource_ids\b", re.IGNORECASE),
    "sources field": re.compile(r"""["']sources["']\s*:""", re.IGNORECASE),
    "source URL": re.compile(r"\bsource\s+url\b", re.IGNORECASE),
    "editorial_status": re.compile(r"\beditorial_status\b", re.IGNORECASE),
    "rewrite_summary": re.compile(r"\brewrite_summary\b", re.IGNORECASE),
    "copyright_note": re.compile(r"\bcopyright_note\b", re.IGNORECASE),
    "internal editorial flags": re.compile(
        r"\binternal\s+editorial\s+flags?\b", re.IGNORECASE
    ),
    "task-work path": re.compile(r"\btask-work(?:[/\\]|\b)", re.IGNORECASE),
    "Windows local path": re.compile(r"\b[A-Za-z]:\\(?:Users|Documents)\\"),
    "Unix local path": re.compile(r"/(?:Users|home)/[^/\s]+/"),
}
GENERATED_MARKER = "<!-- Generated by scripts/learn_glossary.py; do not edit. -->"


class ValidationError(RuntimeError):
    """Raised when glossary or lesson data violates the public contract."""


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def assert_no_forbidden_keys(value: object, location: str = "$") -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            normalized = str(key).strip().lower().replace("-", "_").replace(" ", "_")
            if normalized in FORBIDDEN_KEYS or normalized.startswith("internal_editorial"):
                raise ValidationError(f"Forbidden field {key!r} at {location}")
            assert_no_forbidden_keys(child, f"{location}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            assert_no_forbidden_keys(child, f"{location}[{index}]")


def assert_no_forbidden_text(content: str, label: str) -> None:
    for name, pattern in FORBIDDEN_TEXT_PATTERNS.items():
        if pattern.search(content):
            raise ValidationError(f"Forbidden {name} found in {label}")


def require_string(entry: dict[str, object], key: str, label: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValidationError(f"{label} requires a non-empty {key}")
    return value.strip()


def optional_string(entry: dict[str, object], key: str) -> str | None:
    value = entry.get(key)
    if value is None or value == "":
        return None
    if not isinstance(value, str):
        raise ValidationError(f"{key} must be a string or null")
    return value.strip() or None


def import_public_safe(input_path: Path) -> dict[str, object]:
    digest = sha256_file(input_path)
    if digest != SAFE_INPUT_SHA256:
        raise ValidationError(
            f"Authorized input SHA-256 mismatch: expected {SAFE_INPUT_SHA256}, got {digest}"
        )

    raw = read_json(input_path)
    if not isinstance(raw, dict):
        raise ValidationError("Authorized glossary input must be a JSON object")
    assert_no_forbidden_keys(raw)

    expected_counts = {
        "entry_count": EXPECTED_SOURCE_ENTRIES,
        "canonical_entry_count": EXPECTED_CANONICAL_ENTRIES,
        "alias_entry_count": EXPECTED_ALIAS_ENTRIES,
    }
    for field, expected in expected_counts.items():
        if raw.get(field) != expected:
            raise ValidationError(
                f"Authorized input {field} must be {expected}, got {raw.get(field)!r}"
            )

    source_entries = raw.get("entries")
    if not isinstance(source_entries, list) or len(source_entries) != EXPECTED_SOURCE_ENTRIES:
        raise ValidationError("Authorized input entries do not match the declared count")

    all_slugs: set[str] = set()
    rows_by_slug: dict[str, dict[str, object]] = {}
    canonical_rows: dict[str, dict[str, object]] = {}
    alias_rows: list[dict[str, object]] = []

    for index, raw_entry in enumerate(source_entries):
        if not isinstance(raw_entry, dict):
            raise ValidationError(f"entries[{index}] must be an object")
        label = f"entries[{index}]"
        slug = require_string(raw_entry, "slug", label)
        if slug in all_slugs:
            raise ValidationError(f"Duplicate term slug: {slug}")
        all_slugs.add(slug)
        rows_by_slug[slug] = raw_entry

        canonical_slug = optional_string(raw_entry, "canonical_slug")
        if canonical_slug:
            alias_rows.append(raw_entry)
        else:
            canonical_rows[slug] = raw_entry

    if len(canonical_rows) != EXPECTED_CANONICAL_ENTRIES:
        raise ValidationError("Canonical entry count does not match the public-safe contract")
    if len(alias_rows) != EXPECTED_ALIAS_ENTRIES:
        raise ValidationError("Alias entry count does not match the public-safe contract")

    def resolve_canonical(alias_slug: str) -> str:
        visited = {alias_slug}
        current = rows_by_slug[alias_slug]
        while True:
            target_slug = optional_string(current, "canonical_slug")
            if not target_slug:
                return require_string(current, "slug", f"entry {alias_slug}")
            if target_slug in visited:
                raise ValidationError(
                    f"Alias cycle found while resolving {alias_slug}: {target_slug}"
                )
            target = rows_by_slug.get(target_slug)
            if target is None:
                raise ValidationError(
                    f"Alias {alias_slug} has broken canonical target {target_slug}"
                )
            visited.add(target_slug)
            current = target

    aliases_by_canonical: dict[str, list[dict[str, str]]] = defaultdict(list)
    for alias in alias_rows:
        alias_slug = require_string(alias, "slug", "alias entry")
        immediate_slug = require_string(alias, "canonical_slug", f"alias {alias_slug}")
        immediate_target = rows_by_slug.get(immediate_slug)
        if immediate_target is None:
            raise ValidationError(
                f"Alias {alias_slug} has broken canonical target {immediate_slug}"
            )
        canonical_slug = resolve_canonical(alias_slug)

        declared_term = optional_string(alias, "canonical_term")
        immediate_term = require_string(
            immediate_target, "term", f"target {immediate_slug}"
        )
        if declared_term != immediate_term:
            raise ValidationError(
                f"Alias {alias_slug} names {declared_term!r}, expected {immediate_term!r}"
            )

        public_alias = {
            "slug": alias_slug,
            "term": require_string(alias, "term", f"alias {alias_slug}"),
        }
        usage_note = optional_string(alias, "usage_note")
        if usage_note:
            public_alias["usage_note"] = usage_note
        aliases_by_canonical[canonical_slug].append(public_alias)

    public_entries: list[dict[str, object]] = []
    for slug, canonical in canonical_rows.items():
        public_entry: dict[str, object] = {
            "aliases": sorted(
                aliases_by_canonical.get(slug, []),
                key=lambda item: (item["term"].casefold(), item["slug"]),
            ),
            "category": require_string(canonical, "category", f"canonical {slug}"),
            "definition": require_string(canonical, "definition", f"canonical {slug}"),
            "slug": slug,
            "term": require_string(canonical, "term", f"canonical {slug}"),
        }
        usage_note = optional_string(canonical, "usage_note")
        if usage_note:
            public_entry["usage_note"] = usage_note
        public_entries.append(public_entry)

    public_entries.sort(key=lambda item: (str(item["term"]).casefold(), str(item["slug"])))
    public_data: dict[str, object] = {
        "schema_version": "1.0",
        "entries": public_entries,
    }
    validate_public_data(public_data)
    serialized = json_text(public_data)
    assert_no_forbidden_text(serialized, "tracked public glossary data")
    write_if_changed(PUBLIC_DATA_PATH, serialized)
    return public_data


def validate_public_data(data: object) -> list[dict[str, object]]:
    if not isinstance(data, dict):
        raise ValidationError("Tracked glossary data must be a JSON object")
    assert_no_forbidden_keys(data)
    if set(data) != {"schema_version", "entries"}:
        raise ValidationError("Tracked glossary data must contain only schema_version and entries")
    if data.get("schema_version") != "1.0":
        raise ValidationError("Unsupported tracked glossary schema version")

    entries = data.get("entries")
    if not isinstance(entries, list) or len(entries) != EXPECTED_CANONICAL_ENTRIES:
        raise ValidationError(
            f"Tracked glossary data must contain {EXPECTED_CANONICAL_ENTRIES} entries"
        )

    canonical_slugs: set[str] = set()
    alias_slugs: set[str] = set()
    alias_count = 0
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise ValidationError(f"Tracked glossary entry {index} must be an object")
        unexpected = set(entry) - {
            "aliases",
            "category",
            "definition",
            "slug",
            "term",
            "usage_note",
        }
        if unexpected:
            raise ValidationError(
                f"Tracked glossary entry {index} has unexpected fields: {sorted(unexpected)}"
            )
        slug = require_string(entry, "slug", f"tracked entry {index}")
        require_string(entry, "term", f"tracked entry {slug}")
        require_string(entry, "category", f"tracked entry {slug}")
        require_string(entry, "definition", f"tracked entry {slug}")
        optional_string(entry, "usage_note")
        if slug in canonical_slugs:
            raise ValidationError(f"Duplicate canonical term slug: {slug}")
        canonical_slugs.add(slug)

        aliases = entry.get("aliases")
        if not isinstance(aliases, list):
            raise ValidationError(f"Tracked entry {slug} aliases must be a list")
        for alias in aliases:
            if not isinstance(alias, dict):
                raise ValidationError(f"Tracked entry {slug} has a non-object alias")
            unexpected_alias = set(alias) - {"slug", "term", "usage_note"}
            if unexpected_alias:
                raise ValidationError(
                    f"Alias under {slug} has unexpected fields: {sorted(unexpected_alias)}"
                )
            alias_slug = require_string(alias, "slug", f"alias under {slug}")
            require_string(alias, "term", f"alias {alias_slug}")
            optional_string(alias, "usage_note")
            if alias_slug in alias_slugs or alias_slug in canonical_slugs:
                raise ValidationError(f"Duplicate alias term slug: {alias_slug}")
            alias_slugs.add(alias_slug)
            alias_count += 1

    overlap = canonical_slugs.intersection(alias_slugs)
    if overlap:
        raise ValidationError(f"Canonical and alias slugs overlap: {sorted(overlap)}")
    if alias_count != EXPECTED_ALIAS_ENTRIES:
        raise ValidationError(
            f"Tracked glossary data must contain {EXPECTED_ALIAS_ENTRIES} aliases"
        )
    return entries


def parse_front_matter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValidationError(f"{path.relative_to(REPOSITORY_ROOT)} has no YAML front matter")
    try:
        closing = next(
            index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"
        )
    except StopIteration as error:
        raise ValidationError(
            f"{path.relative_to(REPOSITORY_ROOT)} has unterminated YAML front matter"
        ) from error

    metadata: dict[str, object] = {}
    current_list: str | None = None
    for line in lines[1:closing]:
        list_item = re.match(r"^\s+-\s+(.+?)\s*$", line)
        if list_item and current_list:
            value = list_item.group(1).strip().strip("\"'")
            cast_list = metadata.setdefault(current_list, [])
            if isinstance(cast_list, list):
                cast_list.append(value)
            continue

        field = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):(?:\s*(.*))?$", line)
        if not field:
            if line and not line[0].isspace():
                current_list = None
            continue
        key, raw_value = field.groups()
        value = (raw_value or "").strip()
        if value:
            metadata[key] = value.strip("\"'")
            current_list = None
        else:
            metadata[key] = []
            current_list = key
    return metadata


def route_for_source(path: Path) -> str:
    relative = path.relative_to(SITE_ROOT)
    if path.name == "index.qmd":
        return "/" + relative.parent.as_posix().rstrip("/") + "/"
    return "/" + relative.with_suffix(".html").as_posix()


def discover_lessons() -> list[dict[str, object]]:
    lessons: list[dict[str, object]] = []
    for path in sorted(LEARN_ROOT.rglob("*.qmd")):
        relative = path.relative_to(LEARN_ROOT)
        if (
            relative in {Path("index.qmd"), Path("lesson-finder/index.qmd")}
            or relative.parts[0] == "glossary"
        ):
            continue
        metadata = parse_front_matter(path)
        title = metadata.get("title")
        if not isinstance(title, str) or not title:
            raise ValidationError(f"Lesson {relative.as_posix()} requires a title")

        lesson: dict[str, object] = {
            "path": path,
            "relative_path": relative.as_posix(),
            "route": route_for_source(path),
            "title": title,
        }
        for key in ("categories", "tags", "terms"):
            value = metadata.get(key)
            if not isinstance(value, list) or not value:
                raise ValidationError(
                    f"Lesson {relative.as_posix()} requires a non-empty {key} list"
                )
            if len(value) != len(set(str(item) for item in value)):
                raise ValidationError(
                    f"Lesson {relative.as_posix()} has duplicate {key} values"
                )
            lesson[key] = [str(item) for item in value]
        lessons.append(lesson)

    if not lessons:
        raise ValidationError("No current Learn lessons were discovered")
    return lessons


def discover_research_articles() -> list[dict[str, object]]:
    articles: list[dict[str, object]] = []
    for path in sorted(RESEARCH_ROOT.glob("*.qmd")):
        if path.name == "index.qmd" or path.name.startswith("_"):
            continue
        metadata = parse_front_matter(path)
        title = metadata.get("title")
        if not isinstance(title, str) or not title:
            raise ValidationError(f"Research article {path.name} requires a title")

        terms = metadata.get("terms", [])
        if not isinstance(terms, list):
            raise ValidationError(
                f"Research article {path.name} terms must be a YAML list"
            )
        if len(terms) != len(set(str(item) for item in terms)):
            raise ValidationError(
                f"Research article {path.name} has duplicate term values"
            )

        description = metadata.get("description")
        if not isinstance(description, str) or description in {">", "|"}:
            description = ""
        articles.append(
            {
                "path": path,
                "relative_path": path.relative_to(SITE_ROOT).as_posix(),
                "route": route_for_source(path),
                "title": title,
                "description": description,
                "terms": [str(item) for item in terms],
            }
        )
    if not articles:
        raise ValidationError("No current Research articles were discovered")
    return articles


def canonical_term_maps(
    entries: list[dict[str, object]],
) -> tuple[set[str], dict[str, str]]:
    canonical_slugs = {str(entry["slug"]) for entry in entries}
    alias_to_canonical = {
        str(alias["slug"]): str(entry["slug"])
        for entry in entries
        for alias in entry["aliases"]  # type: ignore[index]
    }
    return canonical_slugs, alias_to_canonical


def validate_lessons(
    lessons: list[dict[str, object]], entries: list[dict[str, object]]
) -> dict[str, list[dict[str, object]]]:
    canonical_slugs, alias_to_canonical = canonical_term_maps(entries)
    related: dict[str, list[dict[str, object]]] = defaultdict(list)

    for lesson in lessons:
        relative = str(lesson["relative_path"])
        invalid_difficulties = set(lesson["categories"]) - set(DIFFICULTIES)
        invalid_tracks = set(lesson["tags"]) - set(TRACKS)
        if invalid_difficulties:
            raise ValidationError(
                f"Lesson {relative} has invalid difficulty categories: "
                f"{sorted(invalid_difficulties)}"
            )
        if invalid_tracks:
            raise ValidationError(
                f"Lesson {relative} has invalid learning-track tags: {sorted(invalid_tracks)}"
            )
        for slug in lesson["terms"]:
            if slug in alias_to_canonical:
                raise ValidationError(
                    f"Lesson {relative} uses alias slug {slug}; "
                    f"use canonical slug {alias_to_canonical[slug]}"
                )
            if slug not in canonical_slugs:
                raise ValidationError(f"Lesson {relative} uses unknown term slug {slug}")
            related[slug].append(lesson)

    for related_lessons in related.values():
        related_lessons.sort(key=lambda lesson: str(lesson["title"]).casefold())
    return related


def validate_research_articles(
    articles: list[dict[str, object]], entries: list[dict[str, object]]
) -> dict[str, list[dict[str, object]]]:
    canonical_slugs, alias_to_canonical = canonical_term_maps(entries)
    related: dict[str, list[dict[str, object]]] = defaultdict(list)

    for article in articles:
        relative = str(article["relative_path"])
        for slug in article["terms"]:
            if slug in alias_to_canonical:
                raise ValidationError(
                    f"Research article {relative} uses alias slug {slug}; "
                    f"use canonical slug {alias_to_canonical[slug]}"
                )
            if slug not in canonical_slugs:
                raise ValidationError(
                    f"Research article {relative} uses unknown term slug {slug}"
                )
            related[slug].append(article)

    for related_articles in related.values():
        related_articles.sort(key=lambda article: str(article["title"]).casefold())
    return related


def display_category(category: str) -> str:
    return category.title().replace(" And ", " and ")


def initial_group(term: str) -> str:
    first = term.strip()[:1].upper()
    return first if "A" <= first <= "Z" else "#"


def html_attr(value: object) -> str:
    return html.escape(str(value), quote=True)


def encoded_query(name: str, value: str) -> str:
    return f"{name}={quote(value, safe='')}"


def lesson_links_html(lessons: list[dict[str, object]], *, compact: bool = False) -> str:
    if not lessons:
        return ""
    item_lines = []
    for lesson in lessons:
        tracks = ", ".join(str(track) for track in lesson["tags"])
        suffix = f" <span>({html.escape(tracks)})</span>" if tracks and not compact else ""
        item_lines.append(
            f'<li><a href="{html_attr(lesson["route"])}">'
            f'{html.escape(str(lesson["title"]))}</a>{suffix}</li>'
        )
    return "\n".join(item_lines)


def research_links_html(articles: list[dict[str, object]]) -> str:
    item_lines = []
    for article in articles:
        description = str(article.get("description", "")).strip()
        description_html = (
            '<span class="bms-glossary-related-description">'
            f"{html.escape(description)}</span>"
            if description
            else ""
        )
        item_lines.append(
            f'<li><a href="{html_attr(article["route"])}">'
            f'{html.escape(str(article["title"]))}</a>{description_html}</li>'
        )
    return "\n".join(item_lines)


def related_sections_html(
    lessons: list[dict[str, object]],
    research_articles: list[dict[str, object]],
) -> list[str]:
    if not lessons and not research_articles:
        return []
    lines = ['<div class="bms-glossary-related-groups">']
    if lessons:
        lines.extend(
            [
                '<details class="bms-glossary-related bms-glossary-related--lessons">',
                f"<summary>Related lessons ({len(lessons)})</summary>",
                "<ul>",
                lesson_links_html(lessons),
                "</ul>",
                "</details>",
            ]
        )
    if research_articles:
        lines.extend(
            [
                '<details class="bms-glossary-related bms-glossary-related--research">',
                f"<summary>Related research ({len(research_articles)})</summary>",
                "<ul>",
                research_links_html(research_articles),
                "</ul>",
                "</details>",
            ]
        )
    lines.append("</div>")
    return lines


def alias_html(aliases: list[dict[str, str]]) -> str:
    if not aliases:
        return ""
    alias_names = ", ".join(
        f'<span id="alias-{html_attr(alias["slug"])}">{html.escape(alias["term"])}</span>'
        for alias in aliases
    )
    return f'<p class="bms-glossary-aliases"><strong>Also called:</strong> {alias_names}</p>'


def usage_notes_html(entry: dict[str, object]) -> str:
    notes: list[str] = []
    if entry.get("usage_note"):
        notes.append(
            '<p class="bms-glossary-usage-note"><strong>Usage note:</strong> '
            f'{html.escape(str(entry["usage_note"]))}</p>'
        )
    for alias in entry["aliases"]:  # type: ignore[index]
        if alias.get("usage_note"):
            notes.append(
                '<p class="bms-glossary-usage-note"><strong>'
                f'{html.escape(str(alias["term"]))}:</strong> '
                f'{html.escape(str(alias["usage_note"]))}</p>'
            )
    return "\n".join(notes)


def build_entries_html(
    entries: list[dict[str, object]],
    related_lessons_by_slug: dict[str, list[dict[str, object]]],
    related_research_by_slug: dict[str, list[dict[str, object]]],
) -> str:
    groups: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in entries:
        groups[initial_group(str(entry["term"]))].append(entry)

    group_order = ["#"] + [chr(code) for code in range(ord("A"), ord("Z") + 1)]
    existing_groups = [group for group in group_order if group in groups]
    alphabet_links = " ".join(
        f'<a href="#letter-{html_attr(group)}" data-bms-letter-link="{html_attr(group)}">'
        f"{html.escape(group)}</a>"
        for group in existing_groups
    )
    lines = [
        GENERATED_MARKER,
        '<nav class="bms-glossary-alphabet" aria-label="Glossary letters">',
        '<div class="bms-glossary-alphabet-links">',
        alphabet_links,
        "</div>",
        '<button type="button" class="bms-glossary-section-control" '
        'data-bms-glossary-section-control aria-controls="bms-glossary-groups" '
        'aria-expanded="true">Collapse all</button>',
        "</nav>",
        '<div class="bms-glossary-groups" id="bms-glossary-groups" data-bms-glossary-groups>',
    ]

    for group in existing_groups:
        group_entries = groups[group]
        lines.extend(
            [
                f'<details class="bms-glossary-letter-group" data-bms-letter-group open '
                f'id="letter-{html_attr(group)}">',
                f"<summary><span>{html.escape(group)}</span>"
                f'<span class="bms-glossary-letter-count">{len(group_entries)} terms</span>'
                "</summary>",
                '<div class="bms-glossary-letter-entries">',
            ]
        )
        for entry in group_entries:
            slug = str(entry["slug"])
            related_lessons = related_lessons_by_slug.get(slug, [])
            related_research = related_research_by_slug.get(slug, [])
            tracks = sorted(
                {
                    str(track)
                    for lesson in related_lessons
                    for track in lesson["tags"]
                },
                key=TRACKS.index,
            )
            search_values = [str(entry["term"])] + [
                str(alias["term"]) for alias in entry["aliases"]  # type: ignore[index]
            ]
            lines.extend(
                [
                    f'<article class="bms-glossary-entry" id="term-{html_attr(slug)}" '
                    f'data-bms-glossary-entry data-bms-slug="{html_attr(slug)}" '
                    f'data-bms-category="{html_attr(entry["category"])}" '
                    f'data-bms-tracks="{html_attr(json.dumps(tracks, ensure_ascii=False))}" '
                    f'data-bms-search="{html_attr(json.dumps(search_values, ensure_ascii=False))}">',
                    f'<h3><a href="/learn/glossary/{html_attr(slug)}/">'
                    f'{html.escape(str(entry["term"]))}</a>'
                    f'<a class="bms-glossary-anchor" href="#term-{html_attr(slug)}" '
                    f'aria-label="Direct link to {html_attr(entry["term"])}">#</a></h3>',
                    alias_html(entry["aliases"]),  # type: ignore[arg-type]
                    f'<p class="bms-glossary-definition">{html.escape(str(entry["definition"]))}</p>',
                    f'<p class="bms-glossary-category"><strong>Category:</strong> '
                    f'<button type="button" data-bms-card-category="{html_attr(entry["category"])}">'
                    f'{html.escape(display_category(str(entry["category"])))}</button></p>',
                    usage_notes_html(entry),
                ]
            )
            lines.extend(related_sections_html(related_lessons, related_research))
            lines.append("</article>")
        lines.extend(["</div>", "</details>"])

    lines.append("</div>")
    content = "\n".join(line for line in lines if line != "") + "\n"
    assert_no_forbidden_text(content, "generated glossary index HTML")
    return content


def build_term_qmd(
    entry: dict[str, object],
    related_lessons: list[dict[str, object]],
    related_research: list[dict[str, object]],
    previous_entry: dict[str, object] | None,
    next_entry: dict[str, object] | None,
) -> str:
    term = str(entry["term"])
    slug = str(entry["slug"])
    canonical_url = (
        "https://backgammon-made-simple.github.io/learn/glossary/" + slug + "/"
    )
    tracks = sorted(
        {
            str(track)
            for lesson in related_lessons
            for track in lesson["tags"]
        },
        key=TRACKS.index,
    )
    lines = [
        "---",
        f"title: {json.dumps(f'What Does {term} Mean in Backgammon?', ensure_ascii=False)}",
        f"description: {json.dumps(str(entry['definition']), ensure_ascii=False)}",
        "sidebar: learn",
        f"canonical-url: {json.dumps(canonical_url)}",
        "image: /assets/social/generated/social-glossary.png",
        'body-classes: "bms-glossary-term"',
        "toc: false",
        "execute:",
        "  enabled: false",
        "---",
        "",
        GENERATED_MARKER,
        "",
        '<span id="bms-glossary-top" class="bms-glossary-top-target" tabindex="-1"></span>',
        "",
        f'<article class="bms-glossary-term-card" id="term-{html_attr(slug)}">',
        f'<p class="bms-glossary-term-name">{html.escape(term)}</p>',
        alias_html(entry["aliases"]),  # type: ignore[arg-type]
        f'<p class="bms-glossary-definition">{html.escape(str(entry["definition"]))}</p>',
        f'<p class="bms-glossary-category"><strong>Glossary category:</strong> '
        f'<a href="/learn/glossary/?{encoded_query("category", str(entry["category"]))}'
        f'#term-{html_attr(slug)}">{html.escape(display_category(str(entry["category"])))}</a></p>',
        usage_notes_html(entry),
    ]
    if tracks:
        track_links = ", ".join(
            f'<a href="/learn/lesson-finder/?{encoded_query("track", track)}">'
            f"{html.escape(track)}</a>"
            for track in tracks
        )
        lines.append(
            f'<p class="bms-glossary-related-tracks"><strong>Learning tracks:</strong> '
            f"{track_links}</p>"
        )
    lines.extend(related_sections_html(related_lessons, related_research))
    lines.extend(
        [
            "</article>",
            "",
            '<nav class="bms-glossary-term-navigation" aria-label="Glossary term navigation">',
        ]
    )
    if previous_entry:
        lines.append(
            f'<a rel="prev" href="/learn/glossary/{html_attr(previous_entry["slug"])}/">'
            f'← {html.escape(str(previous_entry["term"]))}</a>'
        )
    lines.append('<a href="/learn/glossary/">Full glossary</a>')
    if next_entry:
        lines.append(
            f'<a rel="next" href="/learn/glossary/{html_attr(next_entry["slug"])}/">'
            f'{html.escape(str(next_entry["term"]))} →</a>'
        )
    lines.extend(
        [
            "</nav>",
            "",
            '<a class="bms-glossary-back-to-top" href="#bms-glossary-top" '
            'data-bms-glossary-back-to-top hidden>Back to top</a>',
            "",
        ]
    )
    content = "\n".join(line for line in lines if line != "") + "\n"
    assert_no_forbidden_text(content, f"generated term source {slug}")
    return content


def build_authoring_terms(entries: list[dict[str, object]]) -> str:
    lines = [
        "# Canonical Learn Glossary Terms",
        "",
        GENERATED_MARKER,
        "",
        "Use only these canonical slugs in lesson `terms` metadata. "
        "This list is generated from the public-safe glossary data.",
        "",
        "| Term | Canonical slug |",
        "|---|---|",
    ]
    for entry in entries:
        term = str(entry["term"]).replace("|", "\\|")
        slug = str(entry["slug"])
        lines.append(f"| {term} | `{slug}` |")
    content = "\n".join(lines) + "\n"
    assert_no_forbidden_text(content, "generated authoring term list")
    return content


def generated_outputs(
    entries: list[dict[str, object]],
    related_lessons: dict[str, list[dict[str, object]]],
    related_research: dict[str, list[dict[str, object]]],
) -> dict[Path, str]:
    outputs = {
        GENERATED_ENTRIES_PATH: build_entries_html(
            entries, related_lessons, related_research
        ),
        AUTHORING_TERMS_PATH: build_authoring_terms(entries),
        GENERATED_ROUTES_PATH: json_text([str(entry["slug"]) for entry in entries]),
    }
    for index, entry in enumerate(entries):
        previous_entry = entries[index - 1] if index > 0 else None
        next_entry = entries[index + 1] if index + 1 < len(entries) else None
        output_path = GLOSSARY_ROOT / str(entry["slug"]) / "index.qmd"
        outputs[output_path] = build_term_qmd(
            entry,
            related_lessons.get(str(entry["slug"]), []),
            related_research.get(str(entry["slug"]), []),
            previous_entry,
            next_entry,
        )
    return outputs


def remove_stale_routes(current_slugs: set[str]) -> list[Path]:
    removed: list[Path] = []
    if not GENERATED_ROUTES_PATH.exists():
        return removed
    previous = read_json(GENERATED_ROUTES_PATH)
    if not isinstance(previous, list):
        raise ValidationError("Generated route manifest must be a list")
    for stale_slug in sorted(set(map(str, previous)) - current_slugs):
        stale_path = (GLOSSARY_ROOT / stale_slug / "index.qmd").resolve()
        expected_parent = GLOSSARY_ROOT.resolve()
        if stale_path.parent.parent != expected_parent:
            raise ValidationError(f"Unsafe stale generated route: {stale_slug}")
        if not stale_path.exists():
            continue
        content = stale_path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in content:
            raise ValidationError(f"Refusing to remove non-generated route: {stale_path}")
        stale_path.unlink()
        if not any(stale_path.parent.iterdir()):
            stale_path.parent.rmdir()
        removed.append(stale_path)
    return removed


def generate() -> tuple[int, int]:
    data = read_json(PUBLIC_DATA_PATH)
    entries = validate_public_data(data)
    serialized = PUBLIC_DATA_PATH.read_text(encoding="utf-8")
    assert_no_forbidden_text(serialized, "tracked public glossary data")
    lessons = discover_lessons()
    related_lessons = validate_lessons(lessons, entries)
    research_articles = discover_research_articles()
    related_research = validate_research_articles(research_articles, entries)

    outputs = generated_outputs(entries, related_lessons, related_research)
    remove_stale_routes({str(entry["slug"]) for entry in entries})
    changed = sum(write_if_changed(path, content) for path, content in outputs.items())
    return changed, len(outputs)


def validate_generated() -> dict[str, int]:
    data = read_json(PUBLIC_DATA_PATH)
    entries = validate_public_data(data)
    assert_no_forbidden_text(
        PUBLIC_DATA_PATH.read_text(encoding="utf-8"),
        "tracked public glossary data",
    )
    lessons = discover_lessons()
    related_lessons = validate_lessons(lessons, entries)
    research_articles = discover_research_articles()
    related_research = validate_research_articles(research_articles, entries)
    expected = generated_outputs(entries, related_lessons, related_research)

    missing = [path for path in expected if not path.exists()]
    changed = [
        path
        for path, content in expected.items()
        if path.exists() and path.read_text(encoding="utf-8") != content
    ]
    if missing:
        raise ValidationError(
            "Missing generated files: "
            + ", ".join(str(path.relative_to(REPOSITORY_ROOT)) for path in missing[:10])
        )
    if changed:
        raise ValidationError(
            "Generated files are stale: "
            + ", ".join(str(path.relative_to(REPOSITORY_ROOT)) for path in changed[:10])
        )

    canonical_slugs = {str(entry["slug"]) for entry in entries}
    actual_routes = {
        path.parent.name
        for path in GLOSSARY_ROOT.glob("*/index.qmd")
        if GENERATED_MARKER in path.read_text(encoding="utf-8")
    }
    if actual_routes != canonical_slugs:
        raise ValidationError("Generated glossary routes do not match canonical slugs")

    alias_slugs = {
        str(alias["slug"])
        for entry in entries
        for alias in entry["aliases"]  # type: ignore[index]
    }
    duplicate_alias_routes = sorted(alias_slugs.intersection(actual_routes))
    if duplicate_alias_routes:
        raise ValidationError(
            f"Alias routes must not be generated: {duplicate_alias_routes[:10]}"
        )

    route_values = ["/learn/glossary/"] + [
        f"/learn/glossary/{entry['slug']}/" for entry in entries
    ]
    if len(route_values) != len(set(route_values)):
        raise ValidationError("Duplicate generated glossary routes")

    related_lesson_count = sum(len(value) for value in related_lessons.values())
    related_research_count = sum(len(value) for value in related_research.values())
    return {
        "source_entries": EXPECTED_SOURCE_ENTRIES,
        "canonical_entries": len(entries),
        "alias_entries": sum(len(entry["aliases"]) for entry in entries),
        "lessons": len(lessons),
        "research_articles": len(research_articles),
        "related_lesson_links": related_lesson_count,
        "related_research_links": related_research_count,
        "generated_files": len(expected),
    }


def check_rendered(output_root: Path) -> dict[str, int]:
    glossary_output = output_root / "learn" / "glossary"
    if not glossary_output.exists():
        raise ValidationError(f"Rendered glossary output is missing: {glossary_output}")
    data = read_json(PUBLIC_DATA_PATH)
    entries = validate_public_data(data)
    lessons = discover_lessons()
    research_articles = discover_research_articles()
    related_research = validate_research_articles(research_articles, entries)

    html_files = sorted(glossary_output.rglob("*.html"))
    expected_html = 1 + len(entries)
    if len(html_files) != expected_html:
        raise ValidationError(
            f"Expected {expected_html} glossary HTML files, found {len(html_files)}"
        )
    for path in html_files:
        assert_no_forbidden_text(
            path.read_text(encoding="utf-8", errors="replace"),
            f"rendered glossary HTML {path.relative_to(output_root)}",
        )

    sitemap = output_root / "sitemap.xml"
    if not sitemap.exists():
        raise ValidationError("Rendered sitemap.xml is missing")
    sitemap_text = sitemap.read_text(encoding="utf-8")
    missing_urls = [
        f"/learn/glossary/{entry['slug']}/"
        for entry in entries
        if f"/learn/glossary/{entry['slug']}/" not in sitemap_text
    ]
    if missing_urls:
        raise ValidationError(f"Glossary routes missing from sitemap: {missing_urls[:10]}")

    learn_html = sorted((output_root / "learn").rglob("*.html"))
    parsed_pages: dict[Path, tuple[set[str], list[str]]] = {}

    class LinkCollector(HTMLParser):
        def __init__(self) -> None:
            super().__init__(convert_charrefs=True)
            self.ids: set[str] = set()
            self.hrefs: list[str] = []
            self.main_depth = 0

        def handle_starttag(
            self, tag: str, attributes: list[tuple[str, str | None]]
        ) -> None:
            values = dict(attributes)
            if values.get("id"):
                self.ids.add(str(values["id"]))
            if tag == "main" and values.get("id") == "quarto-document-content":
                self.main_depth += 1
            if self.main_depth and values.get("href"):
                self.hrefs.append(str(values["href"]))

        def handle_endtag(self, tag: str) -> None:
            if tag == "main" and self.main_depth:
                self.main_depth -= 1

    def parse_page(path: Path) -> tuple[set[str], list[str]]:
        if path not in parsed_pages:
            collector = LinkCollector()
            collector.feed(path.read_text(encoding="utf-8", errors="replace"))
            parsed_pages[path] = (collector.ids, collector.hrefs)
        return parsed_pages[path]

    broken_links: list[str] = []
    checked_links = 0
    for source in learn_html:
        source_relative = source.relative_to(output_root).as_posix()
        _, hrefs = parse_page(source)
        for href in hrefs:
            if href.startswith(("mailto:", "tel:", "javascript:", "data:")):
                continue
            resolved = urlsplit(
                urljoin(f"https://site.invalid/{source_relative}", href)
            )
            if resolved.netloc != "site.invalid":
                continue
            decoded_path = unquote(resolved.path)
            if decoded_path.endswith("/"):
                target = output_root / decoded_path.lstrip("/") / "index.html"
            else:
                target = output_root / decoded_path.lstrip("/")
                if target.is_dir():
                    target = target / "index.html"
            if not target.exists():
                broken_links.append(
                    f"{source_relative}: {href} -> missing {decoded_path}"
                )
                continue
            checked_links += 1
            if resolved.fragment and target.suffix.lower() == ".html":
                target_ids, _ = parse_page(target)
                fragment = unquote(resolved.fragment)
                if fragment not in target_ids:
                    broken_links.append(
                        f"{source_relative}: {href} -> missing fragment {fragment}"
                    )

    if broken_links:
        raise ValidationError(
            "Broken rendered Learn links: " + " | ".join(broken_links[:20])
        )

    learn_landing_path = output_root / "learn" / "index.html"
    lesson_finder_path = output_root / "learn" / "lesson-finder" / "index.html"
    lesson_path = output_root / "learn" / "cube" / "index.html"
    research_index_path = output_root / "research" / "index.html"
    research_article_path = (
        output_root / "research" / "sage-vs-gnu-additional-details.html"
    )
    glossary_landing_path = glossary_output / "index.html"
    sampled_term_paths = [
        glossary_output / "take-point" / "index.html",
        glossary_output / "equity" / "index.html",
    ]
    amendment_paths = [
        learn_landing_path,
        lesson_finder_path,
        lesson_path,
        research_index_path,
        research_article_path,
        glossary_landing_path,
        *sampled_term_paths,
    ]
    missing_amendment_pages = [path for path in amendment_paths if not path.exists()]
    if missing_amendment_pages:
        raise ValidationError(
            "Missing rendered amendment pages: "
            + ", ".join(
                str(path.relative_to(output_root)) for path in missing_amendment_pages
            )
        )

    learn_landing_html = learn_landing_path.read_text(encoding="utf-8")
    if "data-bms-learn-filters" in learn_landing_html or "data-bms-learn-item" in learn_landing_html:
        raise ValidationError("Rendered Learn landing still contains Lesson Finder controls")
    if "Why We Are Starting With the Doubling Cube" in learn_landing_html:
        raise ValidationError("Rendered Learn landing still has the removed cube section")
    if "Start with The Doubling Cube" not in learn_landing_html:
        raise ValidationError("Rendered Learn landing is missing the replacement cube section")
    if "Find Lessons by Difficulty" not in learn_landing_html:
        raise ValidationError("Rendered Learn landing is missing its Lesson Finder action")
    if (
        'href="/learn/glossary/"' not in learn_landing_html
        or 'target="_blank"' not in learn_landing_html
        or 'rel="noopener"' not in learn_landing_html
    ):
        raise ValidationError("Rendered Learn glossary action violates new-tab policy")

    lesson_finder_html = lesson_finder_path.read_text(encoding="utf-8")
    if "data-bms-learn-filters" not in lesson_finder_html:
        raise ValidationError("Rendered Lesson Finder is missing filter controls")
    if lesson_finder_html.count("data-bms-learn-item") != len(lessons := discover_lessons()):
        raise ValidationError("Rendered Lesson Finder does not contain exactly seven lessons")
    if "bms-learn-card-taxonomy" in lesson_finder_html:
        raise ValidationError("Rendered Lesson Finder exposes taxonomy chips")
    if "combined with <strong>or</strong>" in lesson_finder_html.lower():
        raise ValidationError("Rendered Lesson Finder still exposes Boolean filter copy")

    sidebar_match = re.search(
        r'<nav id="quarto-sidebar".*?</nav>',
        lesson_finder_html,
        flags=re.DOTALL,
    )
    if not sidebar_match:
        raise ValidationError("Rendered Lesson Finder has no Learn sidebar")
    sidebar_html = sidebar_match.group(0)
    home_position = sidebar_html.find("Learn Home")
    finder_position = sidebar_html.rfind("Lesson Finder")
    glossary_position = sidebar_html.rfind("Backgammon Glossary")
    if home_position < 0:
        raise ValidationError("Rendered Learn sidebar is missing Learn Home")
    if finder_position < 0 or finder_position < sidebar_html.rfind("Opening Play Lab"):
        raise ValidationError("Lesson Finder is not second-last in the Learn sidebar")
    if glossary_position < finder_position:
        raise ValidationError("Backgammon Glossary is not last in the Learn sidebar")
    glossary_sidebar_link = re.search(
        r'<a[^>]*href="[^"]*learn/glossary/index\.html"[^>]*>',
        sidebar_html,
    )
    if not glossary_sidebar_link:
        raise ValidationError("Rendered Learn sidebar is missing Backgammon Glossary")
    glossary_sidebar_tag = glossary_sidebar_link.group(0)
    if (
        'target="_blank"' not in glossary_sidebar_tag
        or 'rel="noopener"' not in glossary_sidebar_tag
    ):
        raise ValidationError("Rendered glossary sidebar link violates new-tab policy")

    glossary_landing_html = glossary_landing_path.read_text(encoding="utf-8")
    if "undergoing editorial review" in glossary_landing_html:
        raise ValidationError("Rendered glossary still contains the removed review notice")
    if "data-bms-glossary-section-control" not in glossary_landing_html:
        raise ValidationError("Rendered glossary is missing the Collapse all control")
    alphabet_match = re.search(
        r'<nav class="bms-glossary-alphabet".*?</nav>',
        glossary_landing_html,
        flags=re.DOTALL,
    )
    if (
        not alphabet_match
        or "data-bms-glossary-section-control" not in alphabet_match.group(0)
    ):
        raise ValidationError("Collapse all is not in the A-Z control area")
    for disclosure_name in (
        "data-bms-glossary-category-disclosure",
        "data-bms-glossary-track-disclosure",
    ):
        disclosure = re.search(
            rf"<details[^>]*{disclosure_name}[^>]*>",
            glossary_landing_html,
        )
        if not disclosure or " open" in disclosure.group(0):
            raise ValidationError(
                "Rendered glossary filter disclosures are not initially collapsed"
            )
    if "data-bms-glossary-back-to-top" not in glossary_landing_html:
        raise ValidationError("Rendered glossary is missing its Back to top control")
    letter_tags = re.findall(
        r'<details class="bms-glossary-letter-group"[^>]*>',
        glossary_landing_html,
    )
    if not letter_tags or any(" open" not in tag for tag in letter_tags):
        raise ValidationError("Rendered glossary letter sections are not initially expanded")

    lesson_html = lesson_path.read_text(encoding="utf-8")
    research_index_html = research_index_path.read_text(encoding="utf-8")
    research_article_html = research_article_path.read_text(encoding="utf-8")
    for label, page_html in (
        ("Learn lesson", lesson_html),
        ("Research article", research_article_html),
    ):
        form = re.search(
            r'<form[^>]*data-bms-term-lookup-form[^>]*>',
            page_html,
        )
        if (
            not form
            or 'action="/learn/glossary/"' not in form.group(0)
            or 'target="_blank"' not in form.group(0)
            or 'rel="noopener"' not in form.group(0)
        ):
            raise ValidationError(f"Rendered {label} is missing the term lookup form")
    for label, page_html in (
        ("Learn Home", learn_landing_html),
        ("Lesson Finder", lesson_finder_html),
        ("Glossary landing", glossary_landing_html),
        ("Research listing", research_index_html),
    ):
        if "data-bms-term-lookup-form" in page_html:
            raise ValidationError(f"Rendered {label} unexpectedly has a term lookup form")

    external_link = re.search(
        r'<a[^>]*href="https://github\.com/backgammon-made-simple/'
        r'backgammon-engine-benchmark"[^>]*>',
        research_article_html,
    )
    if (
        not external_link
        or 'target="_blank"' not in external_link.group(0)
        or 'rel="noopener"' not in external_link.group(0)
    ):
        raise ValidationError("Rendered external link violates new-tab policy")
    internal_link = re.search(
        r'<a[^>]*href="\.\./engine-benchmark/sage-vs-gnu-stage1/index\.html"[^>]*>',
        research_article_html,
    )
    if internal_link and 'target="_blank"' in internal_link.group(0):
        raise ValidationError("Rendered ordinary internal link opens in a new tab")

    equity_html = sampled_term_paths[1].read_text(encoding="utf-8")
    expected_research_route = "/research/sage-vs-gnu-additional-details.html"
    if (
        "Related research (1)" not in equity_html
        or expected_research_route not in equity_html
    ):
        raise ValidationError("Rendered Equity term is missing related Research")
    related_research_link = re.search(
        rf'<a[^>]*href="{re.escape(expected_research_route)}"[^>]*>',
        equity_html,
    )
    if related_research_link and 'target="_blank"' in related_research_link.group(0):
        raise ValidationError("Related Research must open in the same tab")

    def meta_content(page_html: str, attribute: str, value: str) -> str:
        pattern = (
            rf'<meta\s+{attribute}="{re.escape(value)}"\s+content="([^"]*)"'
        )
        match = re.search(pattern, page_html)
        if not match:
            raise ValidationError(f"Missing rendered metadata {attribute}={value}")
        return html.unescape(match.group(1))

    shared_image = (
        "https://backgammon-made-simple.github.io/"
        "assets/social/generated/social-glossary.png"
    )
    sampled_metadata: list[dict[str, str]] = []
    for page_path in [glossary_landing_path, *sampled_term_paths]:
        page_html = page_path.read_text(encoding="utf-8")
        metadata = {
            "og_title": meta_content(page_html, "property", "og:title"),
            "og_description": meta_content(page_html, "property", "og:description"),
            "og_image": meta_content(page_html, "property", "og:image"),
            "twitter_title": meta_content(page_html, "name", "twitter:title"),
            "twitter_description": meta_content(
                page_html, "name", "twitter:description"
            ),
            "twitter_image": meta_content(page_html, "name", "twitter:image"),
        }
        if metadata["og_image"] != shared_image or metadata["twitter_image"] != shared_image:
            raise ValidationError(
                f"Rendered page {page_path.relative_to(output_root)} "
                "does not use the shared glossary social image"
            )
        sampled_metadata.append(metadata)

    for term_path, metadata in zip(sampled_term_paths, sampled_metadata[1:]):
        term_html = term_path.read_text(encoding="utf-8")
        slug = term_path.parent.name
        canonical = (
            "https://backgammon-made-simple.github.io/learn/glossary/"
            f"{slug}/"
        )
        if f'<link rel="canonical" href="{canonical}">' not in term_html:
            raise ValidationError(f"Rendered term {slug} is missing its canonical head link")
        if "bms-glossary-canonical" in term_html or "<strong>Canonical URL:" in term_html:
            raise ValidationError(f"Rendered term {slug} still has a visible canonical row")
        if '<div class="description">' not in term_html:
            raise ValidationError(f"Rendered term {slug} lost its metadata description")
        if not metadata["og_title"] or not metadata["og_description"]:
            raise ValidationError(f"Rendered term {slug} has incomplete social metadata")

    take_metadata, equity_metadata = sampled_metadata[1:]
    if take_metadata["og_title"] == equity_metadata["og_title"]:
        raise ValidationError("Sampled term pages have duplicate Open Graph titles")
    if take_metadata["og_description"] == equity_metadata["og_description"]:
        raise ValidationError("Sampled term pages have duplicate Open Graph descriptions")
    if take_metadata["twitter_title"] == equity_metadata["twitter_title"]:
        raise ValidationError("Sampled term pages have duplicate Twitter titles")
    if take_metadata["twitter_description"] == equity_metadata["twitter_description"]:
        raise ValidationError("Sampled term pages have duplicate Twitter descriptions")

    return {
        "html_files": len(html_files),
        "sitemap_routes": len(entries),
        "learn_html_files": len(learn_html),
        "internal_links": checked_links,
        "lesson_finder_items": len(lessons),
        "expanded_letter_groups": len(letter_tags),
        "related_research_links": sum(
            len(value) for value in related_research.values()
        ),
        "sampled_social_pages": len(sampled_metadata),
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    import_parser = subparsers.add_parser(
        "import-public-safe", help="Import the authorized public-safe bundle"
    )
    import_parser.add_argument("--input", required=True, type=Path)

    subparsers.add_parser("generate", help="Regenerate glossary sources")
    subparsers.add_parser("validate", help="Validate data, metadata, and generated sources")

    rendered_parser = subparsers.add_parser(
        "check-rendered", help="Check rendered glossary HTML and sitemap"
    )
    rendered_parser.add_argument("--output", type=Path, default=SITE_ROOT / "_site")

    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    command = args.command or "generate"
    try:
        if command == "import-public-safe":
            data = import_public_safe(args.input.resolve())
            print(
                f"Imported {len(data['entries'])} canonical entries to "
                f"{PUBLIC_DATA_PATH.relative_to(REPOSITORY_ROOT)}"
            )
            return 0
        if command == "generate":
            changed, total = generate()
            print(f"Glossary generation complete: {changed} changed, {total} checked")
            return 0
        if command == "validate":
            result = validate_generated()
            print("Glossary validation passed: " + json.dumps(result, sort_keys=True))
            return 0
        if command == "check-rendered":
            result = check_rendered(args.output.resolve())
            print("Rendered glossary check passed: " + json.dumps(result, sort_keys=True))
            return 0
    except (OSError, json.JSONDecodeError, ValidationError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    raise AssertionError(f"Unhandled command: {command}")


if __name__ == "__main__":
    raise SystemExit(main())
