#!/usr/bin/env python3
"""Import, validate, and generate the Learn glossary from public-safe data."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from urllib.parse import urljoin
from xml.etree import ElementTree

import yaml


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SITE_ROOT = REPOSITORY_ROOT / "site"
LEARN_ROOT = SITE_ROOT / "learn"
CUBE_ROOT = LEARN_ROOT / "cube"
RESEARCH_ROOT = SITE_ROOT / "research"
GLOSSARY_ROOT = LEARN_ROOT / "glossary"
PUBLIC_DATA_PATH = SITE_ROOT / "data" / "glossary.json"
AUTHORING_TERMS_PATH = REPOSITORY_ROOT / "docs" / "learn-glossary-terms.md"
GENERATED_ENTRIES_PATH = GLOSSARY_ROOT / "_entries.html"
GENERATED_LESSON_CATALOGUE_PATH = LEARN_ROOT / "_lesson-catalogue.html"
GENERATED_NAVIGATION_PATH = SITE_ROOT / "_learn-navigation.yml"
LEGACY_GENERATED_ROUTES_PATH = GLOSSARY_ROOT / "_generated-routes.json"
QUARTO_CONFIG_PATH = SITE_ROOT / "_quarto.yml"

SAFE_INPUT_SHA256 = "ce10ecccc983ab87b7a43bfb46a04e91b44a00d93ba9ee86765638be991595e4"
EXPECTED_SOURCE_ENTRIES = 805
EXPECTED_CANONICAL_ENTRIES = 624
EXPECTED_ALIAS_ENTRIES = 181
FULL_BUILD_MARKER_NAME = ".bms-full-build.json"
FULL_BUILD_MARKER_SCHEMA = 1
RENDERED_CORE_PATHS = (
    "index.html",
    "about.html",
    "learn/index.html",
    "learn/start-here/index.html",
    "learn/glossary/index.html",
    "learn/cube/index.html",
    "learn/opening-play/index.html",
    "learn/cube/why-is-25-percent-the-basic-take-point.html",
    "research/index.html",
    "research/sage-vs-gnu-additional-details.html",
    "updates/index.html",
)
RSS_FOOTER_REPRESENTATIVE_PATHS = (
    "index.html",
    "about.html",
    "learn/index.html",
    "learn/cube/index.html",
    "learn/glossary/index.html",
    "research/index.html",
    "updates/index.html",
)
NOT_FOUND_ROUTES = (
    "/",
    "/learn/",
    "/learn/glossary/",
    "/research/",
)

DIFFICULTIES = ("Beginner", "Intermediate", "Advanced")
TRACKS = (
    "Doubling Cube",
    "Checker Play",
    "Opening Play",
    "Match Play",
    "Endgames",
    "Engines and Analysis",
)

FORBIDDEN_KEYS = {
    "source_ids",
    "sources",
    "source_url",
    "editorial_status",
    "rewrite_summary",
    "copyright_note",
}
FORBIDDEN_TEXT_PATTERNS = {
    "source_ids": re.compile(r"\bsource_ids\b", re.IGNORECASE),
    "sources field": re.compile(r"""["']sources["']\s*:""", re.IGNORECASE),
    "source URL": re.compile(r"\bsource\s+url\b", re.IGNORECASE),
    "editorial_status": re.compile(r"\beditorial_status\b", re.IGNORECASE),
    "rewrite_summary": re.compile(r"\brewrite_summary\b", re.IGNORECASE),
    "copyright_note": re.compile(r"\bcopyright_note\b", re.IGNORECASE),
    "internal editorial flags": re.compile(
        r"\binternal\s+editorial\s+flags?\b", re.IGNORECASE
    ),
    "task-work path": re.compile(r"\btask-work(?:[/\\]|\b)", re.IGNORECASE),
    "Windows local path": re.compile(r"\b[A-Za-z]:\\(?:Users|Documents)\\"),
    "Unix local path": re.compile(r"/(?:Users|home)/[^/\s]+/"),
}
GENERATED_MARKER = "<!-- Generated by scripts/learn_glossary.py; do not edit. -->"


class ValidationError(RuntimeError):
    """Raised when glossary or lesson data violates the public contract."""


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def json_text(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def assert_no_forbidden_keys(value: object, location: str = "$") -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            normalized = str(key).strip().lower().replace("-", "_").replace(" ", "_")
            if normalized in FORBIDDEN_KEYS or normalized.startswith("internal_editorial"):
                raise ValidationError(f"Forbidden field {key!r} at {location}")
            assert_no_forbidden_keys(child, f"{location}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            assert_no_forbidden_keys(child, f"{location}[{index}]")


def assert_no_forbidden_text(content: str, label: str) -> None:
    for name, pattern in FORBIDDEN_TEXT_PATTERNS.items():
        if pattern.search(content):
            raise ValidationError(f"Forbidden {name} found in {label}")


def require_string(entry: dict[str, object], key: str, label: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ValidationError(f"{label} requires a non-empty {key}")
    return value.strip()


def optional_string(entry: dict[str, object], key: str) -> str | None:
    value = entry.get(key)
    if value is None or value == "":
        return None
    if not isinstance(value, str):
        raise ValidationError(f"{key} must be a string or null")
    return value.strip() or None


def import_public_safe(input_path: Path) -> dict[str, object]:
    digest = sha256_file(input_path)
    if digest != SAFE_INPUT_SHA256:
        raise ValidationError(
            f"Authorized input SHA-256 mismatch: expected {SAFE_INPUT_SHA256}, got {digest}"
        )

    raw = read_json(input_path)
    if not isinstance(raw, dict):
        raise ValidationError("Authorized glossary input must be a JSON object")
    assert_no_forbidden_keys(raw)

    expected_counts = {
        "entry_count": EXPECTED_SOURCE_ENTRIES,
        "canonical_entry_count": EXPECTED_CANONICAL_ENTRIES,
        "alias_entry_count": EXPECTED_ALIAS_ENTRIES,
    }
    for field, expected in expected_counts.items():
        if raw.get(field) != expected:
            raise ValidationError(
                f"Authorized input {field} must be {expected}, got {raw.get(field)!r}"
            )

    source_entries = raw.get("entries")
    if not isinstance(source_entries, list) or len(source_entries) != EXPECTED_SOURCE_ENTRIES:
        raise ValidationError("Authorized input entries do not match the declared count")

    all_slugs: set[str] = set()
    rows_by_slug: dict[str, dict[str, object]] = {}
    canonical_rows: dict[str, dict[str, object]] = {}
    alias_rows: list[dict[str, object]] = []

    for index, raw_entry in enumerate(source_entries):
        if not isinstance(raw_entry, dict):
            raise ValidationError(f"entries[{index}] must be an object")
        label = f"entries[{index}]"
        slug = require_string(raw_entry, "slug", label)
        if slug in all_slugs:
            raise ValidationError(f"Duplicate term slug: {slug}")
        all_slugs.add(slug)
        rows_by_slug[slug] = raw_entry

        canonical_slug = optional_string(raw_entry, "canonical_slug")
        if canonical_slug:
            alias_rows.append(raw_entry)
        else:
            canonical_rows[slug] = raw_entry

    if len(canonical_rows) != EXPECTED_CANONICAL_ENTRIES:
        raise ValidationError("Canonical entry count does not match the public-safe contract")
    if len(alias_rows) != EXPECTED_ALIAS_ENTRIES:
        raise ValidationError("Alias entry count does not match the public-safe contract")

    def resolve_canonical(alias_slug: str) -> str:
        visited = {alias_slug}
        current = rows_by_slug[alias_slug]
        while True:
            target_slug = optional_string(current, "canonical_slug")
            if not target_slug:
                return require_string(current, "slug", f"entry {alias_slug}")
            if target_slug in visited:
                raise ValidationError(
                    f"Alias cycle found while resolving {alias_slug}: {target_slug}"
                )
            target = rows_by_slug.get(target_slug)
            if target is None:
                raise ValidationError(
                    f"Alias {alias_slug} has broken canonical target {target_slug}"
                )
            visited.add(target_slug)
            current = target

    aliases_by_canonical: dict[str, list[dict[str, str]]] = defaultdict(list)
    for alias in alias_rows:
        alias_slug = require_string(alias, "slug", "alias entry")
        immediate_slug = require_string(alias, "canonical_slug", f"alias {alias_slug}")
        immediate_target = rows_by_slug.get(immediate_slug)
        if immediate_target is None:
            raise ValidationError(
                f"Alias {alias_slug} has broken canonical target {immediate_slug}"
            )
        canonical_slug = resolve_canonical(alias_slug)

        declared_term = optional_string(alias, "canonical_term")
        immediate_term = require_string(
            immediate_target, "term", f"target {immediate_slug}"
        )
        if declared_term != immediate_term:
            raise ValidationError(
                f"Alias {alias_slug} names {declared_term!r}, expected {immediate_term!r}"
            )

        public_alias = {
            "slug": alias_slug,
            "term": require_string(alias, "term", f"alias {alias_slug}"),
        }
        usage_note = optional_string(alias, "usage_note")
        if usage_note:
            public_alias["usage_note"] = usage_note
        aliases_by_canonical[canonical_slug].append(public_alias)

    public_entries: list[dict[str, object]] = []
    for slug, canonical in canonical_rows.items():
        public_entry: dict[str, object] = {
            "aliases": sorted(
                aliases_by_canonical.get(slug, []),
                key=lambda item: (item["term"].casefold(), item["slug"]),
            ),
            "category": require_string(canonical, "category", f"canonical {slug}"),
            "definition": require_string(canonical, "definition", f"canonical {slug}"),
            "slug": slug,
            "term": require_string(canonical, "term", f"canonical {slug}"),
        }
        usage_note = optional_string(canonical, "usage_note")
        if usage_note:
            public_entry["usage_note"] = usage_note
        public_entries.append(public_entry)

    public_entries.sort(key=lambda item: (str(item["term"]).casefold(), str(item["slug"])))
    public_data: dict[str, object] = {
        "schema_version": "1.0",
        "entries": public_entries,
    }
    validate_public_data(public_data)
    serialized = json_text(public_data)
    assert_no_forbidden_text(serialized, "tracked public glossary data")
    write_if_changed(PUBLIC_DATA_PATH, serialized)
    return public_data


def validate_public_data(data: object) -> list[dict[str, object]]:
    if not isinstance(data, dict):
        raise ValidationError("Tracked glossary data must be a JSON object")
    assert_no_forbidden_keys(data)
    if set(data) != {"schema_version", "entries"}:
        raise ValidationError("Tracked glossary data must contain only schema_version and entries")
    if data.get("schema_version") != "1.0":
        raise ValidationError("Unsupported tracked glossary schema version")

    entries = data.get("entries")
    if not isinstance(entries, list) or len(entries) != EXPECTED_CANONICAL_ENTRIES:
        raise ValidationError(
            f"Tracked glossary data must contain {EXPECTED_CANONICAL_ENTRIES} entries"
        )

    canonical_slugs: set[str] = set()
    alias_slugs: set[str] = set()
    alias_count = 0
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise ValidationError(f"Tracked glossary entry {index} must be an object")
        unexpected = set(entry) - {
            "aliases",
            "category",
            "definition",
            "slug",
            "term",
            "usage_note",
        }
        if unexpected:
            raise ValidationError(
                f"Tracked glossary entry {index} has unexpected fields: {sorted(unexpected)}"
            )
        slug = require_string(entry, "slug", f"tracked entry {index}")
        require_string(entry, "term", f"tracked entry {slug}")
        require_string(entry, "category", f"tracked entry {slug}")
        require_string(entry, "definition", f"tracked entry {slug}")
        optional_string(entry, "usage_note")
        if slug in canonical_slugs:
            raise ValidationError(f"Duplicate canonical term slug: {slug}")
        canonical_slugs.add(slug)

        aliases = entry.get("aliases")
        if not isinstance(aliases, list):
            raise ValidationError(f"Tracked entry {slug} aliases must be a list")
        for alias in aliases:
            if not isinstance(alias, dict):
                raise ValidationError(f"Tracked entry {slug} has a non-object alias")
            unexpected_alias = set(alias) - {"slug", "term", "usage_note"}
            if unexpected_alias:
                raise ValidationError(
                    f"Alias under {slug} has unexpected fields: {sorted(unexpected_alias)}"
                )
            alias_slug = require_string(alias, "slug", f"alias under {slug}")
            require_string(alias, "term", f"alias {alias_slug}")
            optional_string(alias, "usage_note")
            if alias_slug in alias_slugs or alias_slug in canonical_slugs:
                raise ValidationError(f"Duplicate alias term slug: {alias_slug}")
            alias_slugs.add(alias_slug)
            alias_count += 1

    overlap = canonical_slugs.intersection(alias_slugs)
    if overlap:
        raise ValidationError(f"Canonical and alias slugs overlap: {sorted(overlap)}")
    if alias_count != EXPECTED_ALIAS_ENTRIES:
        raise ValidationError(
            f"Tracked glossary data must contain {EXPECTED_ALIAS_ENTRIES} aliases"
        )
    return entries


def parse_front_matter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValidationError(f"{path.relative_to(REPOSITORY_ROOT)} has no YAML front matter")
    try:
        closing = next(
            index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"
        )
    except StopIteration as error:
        raise ValidationError(
            f"{path.relative_to(REPOSITORY_ROOT)} has unterminated YAML front matter"
        ) from error

    metadata: dict[str, object] = {}
    current_list: str | None = None
    for line in lines[1:closing]:
        list_item = re.match(r"^\s+-\s+(.+?)\s*$", line)
        if list_item and current_list:
            value = list_item.group(1).strip().strip("\"'")
            cast_list = metadata.setdefault(current_list, [])
            if isinstance(cast_list, list):
                cast_list.append(value)
            continue

        field = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):(?:\s*(.*))?$", line)
        if not field:
            if line and not line[0].isspace():
                current_list = None
            continue
        key, raw_value = field.groups()
        value = (raw_value or "").strip()
        if value:
            metadata[key] = value.strip("\"'")
            current_list = None
        else:
            metadata[key] = []
            current_list = key
    return metadata


def parse_complete_front_matter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValidationError(f"{path.relative_to(REPOSITORY_ROOT)} has no YAML front matter")
    try:
        closing = next(
            index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"
        )
        metadata = yaml.load("\n".join(lines[1:closing]), Loader=yaml.BaseLoader)
    except StopIteration as error:
        raise ValidationError(
            f"{path.relative_to(REPOSITORY_ROOT)} has unterminated YAML front matter"
        ) from error
    except yaml.YAMLError as error:
        raise ValidationError(
            f"{path.relative_to(REPOSITORY_ROOT)} has invalid YAML front matter"
        ) from error
    if not isinstance(metadata, dict):
        raise ValidationError(
            f"{path.relative_to(REPOSITORY_ROOT)} front matter must be a mapping"
        )
    return {str(key): value for key, value in metadata.items()}


def route_for_source(path: Path) -> str:
    relative = path.relative_to(SITE_ROOT)
    if path.name == "index.qmd":
        return "/" + relative.parent.as_posix().rstrip("/") + "/"
    return "/" + relative.with_suffix(".html").as_posix()


def positive_integer(value: object, label: str) -> int:
    try:
        parsed = int(str(value))
    except (TypeError, ValueError) as error:
        raise ValidationError(f"{label} requires a positive integer") from error
    if parsed < 1:
        raise ValidationError(f"{label} requires a positive integer")
    return parsed


def discover_tracks() -> list[dict[str, object]]:
    tracks: list[dict[str, object]] = []
    ids: set[str] = set()
    orders: set[int] = set()
    for path in sorted(LEARN_ROOT.rglob("*.qmd")):
        metadata = parse_complete_front_matter(path)
        track_id = metadata.get("learn-track-index")
        if not isinstance(track_id, str) or not track_id.strip():
            continue
        track_id = track_id.strip()
        order = positive_integer(
            metadata.get("learn-track-order"),
            f"Track index {path.relative_to(LEARN_ROOT).as_posix()} learn-track-order",
        )
        if track_id in ids:
            raise ValidationError(f"Duplicate Learn track id {track_id!r}")
        if order in orders:
            raise ValidationError(f"Duplicate Learn track order {order}")
        title = metadata.get("title")
        description = metadata.get("description")
        if not isinstance(title, str) or not title.strip():
            raise ValidationError(f"Track index {track_id} requires a title")
        if not isinstance(description, str) or not description.strip():
            raise ValidationError(f"Track index {track_id} requires a description")
        ids.add(track_id)
        orders.add(order)
        tracks.append(
            {
                "id": track_id,
                "order": order,
                "path": path,
                "relative_path": path.relative_to(LEARN_ROOT).as_posix(),
                "source_path": path.relative_to(SITE_ROOT).as_posix(),
                "route": route_for_source(path),
                "title": title.strip(),
                "description": " ".join(description.split()),
            }
        )
    tracks.sort(key=lambda track: int(track["order"]))
    if not tracks:
        raise ValidationError("No Learn track index pages were discovered")
    if [int(track["order"]) for track in tracks] != list(
        range(1, len(tracks) + 1)
    ):
        raise ValidationError("Learn track orders must be contiguous from 1")
    return tracks


def discover_lessons() -> list[dict[str, object]]:
    lessons: list[dict[str, object]] = []
    for path in sorted(LEARN_ROOT.rglob("*.qmd")):
        relative = path.relative_to(LEARN_ROOT)
        if (
            relative == Path("index.qmd")
            or relative.parts[0] == "glossary"
        ):
            continue
        complete_metadata = parse_complete_front_matter(path)
        if complete_metadata.get("learn-track-index"):
            continue
        metadata = parse_front_matter(path)
        title = complete_metadata.get("title")
        if not isinstance(title, str) or not title:
            raise ValidationError(f"Lesson {relative.as_posix()} requires a title")
        track_id = complete_metadata.get("learn-track")
        if not isinstance(track_id, str) or not track_id.strip():
            raise ValidationError(
                f"Lesson {relative.as_posix()} requires learn-track"
            )
        order = positive_integer(
            complete_metadata.get("learn-order"),
            f"Lesson {relative.as_posix()} learn-order",
        )

        lesson: dict[str, object] = {
            "path": path,
            "relative_path": relative.as_posix(),
            "source_path": path.relative_to(SITE_ROOT).as_posix(),
            "route": route_for_source(path),
            "title": title,
            "track_id": track_id.strip(),
            "order": order,
        }
        description = complete_metadata.get("description")
        if not isinstance(description, str) or not description.strip():
            raise ValidationError(
                f"Lesson {relative.as_posix()} requires a description"
            )
        lesson["description"] = " ".join(description.split())
        for key in ("categories", "tags", "terms"):
            value = metadata.get(key)
            if not isinstance(value, list) or not value:
                raise ValidationError(
                    f"Lesson {relative.as_posix()} requires a non-empty {key} list"
                )
            if len(value) != len(set(str(item) for item in value)):
                raise ValidationError(
                    f"Lesson {relative.as_posix()} has duplicate {key} values"
                )
            lesson[key] = [str(item) for item in value]
        lessons.append(lesson)

    if not lessons:
        raise ValidationError("No current Learn lessons were discovered")
    return lessons


def build_curriculum(
    tracks: list[dict[str, object]],
    lessons: list[dict[str, object]],
) -> list[dict[str, object]]:
    track_by_id = {str(track["id"]): track for track in tracks}
    lessons_by_track: dict[str, list[dict[str, object]]] = defaultdict(list)
    lesson_orders: dict[str, set[int]] = defaultdict(set)
    for lesson in lessons:
        track_id = str(lesson["track_id"])
        if track_id not in track_by_id:
            raise ValidationError(
                f"Lesson {lesson['relative_path']} uses unknown learn-track {track_id!r}"
            )
        order = int(lesson["order"])
        if order in lesson_orders[track_id]:
            raise ValidationError(
                f"Learn track {track_id!r} has duplicate lesson order {order}"
            )
        lesson_orders[track_id].add(order)
        lessons_by_track[track_id].append(lesson)

    curriculum: list[dict[str, object]] = []
    for track in tracks:
        track_lessons = lessons_by_track[str(track["id"])]
        track_lessons.sort(key=lambda lesson: int(lesson["order"]))
        expected_orders = list(range(1, len(track_lessons) + 1))
        if [int(lesson["order"]) for lesson in track_lessons] != expected_orders:
            raise ValidationError(
                f"Learn track {track['id']!r} lesson orders must be contiguous from 1"
            )
        curriculum.append({**track, "lessons": track_lessons})
    return curriculum


def discover_cube_lessons() -> list[dict[str, object]]:
    tracks = discover_tracks()
    lessons = discover_lessons()
    curriculum = build_curriculum(tracks, lessons)
    for track in curriculum:
        if track["id"] != "doubling-cube":
            continue
        track_lessons = track["lessons"]
        if not isinstance(track_lessons, list) or not track_lessons:
            raise ValidationError("No published cube lessons were discovered")
        return [
            {
                **lesson,
                "relative_path": Path(str(lesson["relative_path"]))
                .relative_to("cube")
                .as_posix(),
                "cube-order": lesson["order"],
            }
            for lesson in track_lessons
        ]
    raise ValidationError("The doubling-cube Learn track was not discovered")


def discover_update_publications() -> list[dict[str, object]]:
    publications: list[dict[str, object]] = []
    excluded_landings = {
        LEARN_ROOT / "index.qmd",
        LEARN_ROOT / "glossary" / "index.qmd",
        RESEARCH_ROOT / "index.qmd",
        SITE_ROOT / "engine-benchmark" / "index.qmd",
    }
    excluded_landings.update(
        track["path"]
        for track in discover_tracks()
        if isinstance(track["path"], Path)
    )
    roots = (
        ("Learn", LEARN_ROOT),
        ("Research", RESEARCH_ROOT),
        ("Benchmark", SITE_ROOT / "engine-benchmark"),
    )
    for publication_type, root in roots:
        for path in sorted(root.rglob("*.qmd")):
            if path.name.startswith("_"):
                continue
            metadata = parse_front_matter(path)
            if str(metadata.get("published", "")).casefold() != "true":
                continue
            if path in excluded_landings:
                raise ValidationError(
                    f"Landing page {path.relative_to(SITE_ROOT)} cannot be an "
                    "Updates publication"
                )
            if str(metadata.get("draft", "")).casefold() == "true":
                raise ValidationError(
                    f"Published update {path.relative_to(SITE_ROOT)} is also a draft"
                )
            if str(metadata.get("hidden", "")).casefold() == "true":
                raise ValidationError(
                    f"Published update {path.relative_to(SITE_ROOT)} is hidden"
                )
            if str(metadata.get("status", "")).casefold() in {"draft", "planned"}:
                raise ValidationError(
                    f"Published update {path.relative_to(SITE_ROOT)} has "
                    f"status {metadata.get('status')!r}"
                )

            title = metadata.get("title")
            raw_date = metadata.get("date")
            if not isinstance(title, str) or not title:
                raise ValidationError(
                    f"Published update {path.relative_to(SITE_ROOT)} requires a title"
                )
            if not isinstance(raw_date, str) or not raw_date:
                raise ValidationError(
                    f"Published update {path.relative_to(SITE_ROOT)} requires a date"
                )
            try:
                publication_date = date.fromisoformat(raw_date)
            except ValueError as error:
                raise ValidationError(
                    f"Published update {path.relative_to(SITE_ROOT)} has invalid "
                    f"date {raw_date!r}"
                ) from error

            publications.append(
                {
                    "date": publication_date.isoformat(),
                    "path": path,
                    "publication_type": publication_type,
                    "route": route_for_source(path),
                    "title": title,
                }
            )

    publications.sort(
        key=lambda publication: (
            -date.fromisoformat(str(publication["date"])).toordinal(),
            str(publication["title"]).casefold(),
            str(publication["route"]),
        )
    )
    return publications


def discover_research_articles() -> list[dict[str, object]]:
    articles: list[dict[str, object]] = []
    for path in sorted(RESEARCH_ROOT.glob("*.qmd")):
        if path.name == "index.qmd" or path.name.startswith("_"):
            continue
        metadata = parse_front_matter(path)
        title = metadata.get("title")
        if not isinstance(title, str) or not title:
            raise ValidationError(f"Research article {path.name} requires a title")

        terms = metadata.get("terms", [])
        if not isinstance(terms, list):
            raise ValidationError(
                f"Research article {path.name} terms must be a YAML list"
            )
        if len(terms) != len(set(str(item) for item in terms)):
            raise ValidationError(
                f"Research article {path.name} has duplicate term values"
            )

        description = metadata.get("description")
        if not isinstance(description, str) or description in {">", "|"}:
            description = ""
        articles.append(
            {
                "path": path,
                "relative_path": path.relative_to(SITE_ROOT).as_posix(),
                "route": route_for_source(path),
                "title": title,
                "description": description,
                "terms": [str(item) for item in terms],
            }
        )
    if not articles:
        raise ValidationError("No current Research articles were discovered")
    return articles


def canonical_term_maps(
    entries: list[dict[str, object]],
) -> tuple[set[str], dict[str, str]]:
    canonical_slugs = {str(entry["slug"]) for entry in entries}
    alias_to_canonical = {
        str(alias["slug"]): str(entry["slug"])
        for entry in entries
        for alias in entry["aliases"]  # type: ignore[index]
    }
    return canonical_slugs, alias_to_canonical


def validate_lessons(
    lessons: list[dict[str, object]], entries: list[dict[str, object]]
) -> dict[str, list[dict[str, object]]]:
    canonical_slugs, alias_to_canonical = canonical_term_maps(entries)
    related: dict[str, list[dict[str, object]]] = defaultdict(list)

    for lesson in lessons:
        relative = str(lesson["relative_path"])
        invalid_difficulties = set(lesson["categories"]) - set(DIFFICULTIES)
        invalid_tracks = set(lesson["tags"]) - set(TRACKS)
        if invalid_difficulties:
            raise ValidationError(
                f"Lesson {relative} has invalid difficulty categories: "
                f"{sorted(invalid_difficulties)}"
            )
        if invalid_tracks:
            raise ValidationError(
                f"Lesson {relative} has invalid learning-track tags: {sorted(invalid_tracks)}"
            )
        for slug in lesson["terms"]:
            if slug in alias_to_canonical:
                raise ValidationError(
                    f"Lesson {relative} uses alias slug {slug}; "
                    f"use canonical slug {alias_to_canonical[slug]}"
                )
            if slug not in canonical_slugs:
                raise ValidationError(f"Lesson {relative} uses unknown term slug {slug}")
            related[slug].append(lesson)

    for related_lessons in related.values():
        related_lessons.sort(key=lambda lesson: str(lesson["title"]).casefold())
    return related


def validate_research_articles(
    articles: list[dict[str, object]], entries: list[dict[str, object]]
) -> dict[str, list[dict[str, object]]]:
    canonical_slugs, alias_to_canonical = canonical_term_maps(entries)
    related: dict[str, list[dict[str, object]]] = defaultdict(list)

    for article in articles:
        relative = str(article["relative_path"])
        for slug in article["terms"]:
            if slug in alias_to_canonical:
                raise ValidationError(
                    f"Research article {relative} uses alias slug {slug}; "
                    f"use canonical slug {alias_to_canonical[slug]}"
                )
            if slug not in canonical_slugs:
                raise ValidationError(
                    f"Research article {relative} uses unknown term slug {slug}"
                )
            related[slug].append(article)

    for related_articles in related.values():
        related_articles.sort(key=lambda article: str(article["title"]).casefold())
    return related


def display_category(category: str) -> str:
    return category.title().replace(" And ", " and ")


def initial_group(term: str) -> str:
    first = term.strip()[:1].upper()
    return first if "A" <= first <= "Z" else "#"


def html_attr(value: object) -> str:
    return html.escape(str(value), quote=True)


def roman_number(value: int, *, uppercase: bool = True) -> str:
    numerals = (
        (1000, "M"),
        (900, "CM"),
        (500, "D"),
        (400, "CD"),
        (100, "C"),
        (90, "XC"),
        (50, "L"),
        (40, "XL"),
        (10, "X"),
        (9, "IX"),
        (5, "V"),
        (4, "IV"),
        (1, "I"),
    )
    remainder = value
    result: list[str] = []
    for number, numeral in numerals:
        while remainder >= number:
            result.append(numeral)
            remainder -= number
    joined = "".join(result)
    return joined if uppercase else joined.lower()


def lesson_filter_button(kind: str, value: str, label: str | None = None) -> str:
    data_attributes = {
        "difficulty": "data-bms-filter-difficulty",
        "track": "data-bms-filter-track",
        "term": "data-bms-filter-term",
    }
    if kind not in data_attributes:
        raise ValidationError(f"Unsupported Learn filter kind {kind!r}")
    modifier_class = f" bms-learn-filter--{kind}"
    return (
        f'<button type="button" class="bms-learn-filter{modifier_class}" '
        f'{data_attributes[kind]}="{html_attr(value)}" aria-pressed="false">'
        f"<span>{html.escape(label or value)}</span>"
        '<span class="bms-learn-filter-count" aria-hidden="true">&times;0</span>'
        "</button>"
    )


def filter_disclosure_html(
    label: str,
    kind: str,
    values: list[tuple[str, str]],
) -> list[str]:
    lines = [
        '<details class="bms-learn-filter-disclosure">',
        f"<summary>{html.escape(label)}</summary>",
        f'<div class="bms-learn-filter-options" role="group" '
        f'aria-label="{html_attr(label)}">',
    ]
    if values:
        lines.extend(
            lesson_filter_button(kind, value, display)
            for value, display in values
        )
    else:
        lines.append('<span class="bms-learn-filter-none">No options yet</span>')
    lines.extend(["</div>", "</details>"])
    return lines


def lesson_catalogue_item_html(
    lesson: dict[str, object],
    term_names: dict[str, str],
) -> list[str]:
    difficulties = [str(value) for value in lesson["categories"]]
    tags = [str(value) for value in lesson["tags"]]
    terms = [str(value) for value in lesson["terms"]]
    search_values = [
        str(lesson["title"]),
        str(lesson["description"]),
        *difficulties,
        *tags,
        *(term_names[slug] for slug in terms),
    ]
    title = str(lesson["title"])
    return [
        f'<article class="bms-learn-catalogue-item" data-bms-learn-item '
        f'data-bms-difficulties="{html_attr(json.dumps(difficulties, ensure_ascii=False))}" '
        f'data-bms-track="{html_attr(lesson["track_id"])}" '
        f'data-bms-terms="{html_attr(json.dumps(terms, ensure_ascii=False))}" '
        f'data-bms-search="{html_attr(json.dumps(search_values, ensure_ascii=False))}">',
        '<div class="bms-learn-catalogue-title-row">',
        f'<span class="bms-learn-lesson-number" aria-hidden="true">'
        f'{roman_number(int(lesson["order"]), uppercase=False)}</span>',
        '<details class="bms-learn-catalogue-description">',
        f'<summary><a class="bms-learn-catalogue-link" '
        f'href="{html_attr(lesson["route"])}">{html.escape(title)}</a>'
        f'<span class="bms-learn-description-arrow" '
        f'aria-label="Show description for {html_attr(title)}">&#9662;</span>'
        "</summary>",
        f"<p>{html.escape(str(lesson['description']))}</p>",
        "</details>",
        "</div>",
        "</article>",
    ]


def build_navigation_yaml(curriculum: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/learn_glossary.py; do not edit.",
        "website:",
        "  sidebar:",
        "    - id: learn",
        '      title: "Learn"',
        "      style: docked",
        "      collapse-level: 2",
        "      contents:",
        '        - text: "Learn Home"',
        "          href: learn/index.qmd",
    ]
    for track in curriculum:
        prefix = roman_number(int(track["order"]))
        lines.extend(
            [
                f'        - section: "{prefix} {str(track["title"]).replace(chr(34), chr(39))}"',
                f"          href: {track['source_path']}",
            ]
        )
        track_lessons = track["lessons"]
        if not isinstance(track_lessons, list):
            raise ValidationError(f"Track {track['id']} has invalid lessons")
        if track_lessons:
            lines.append("          contents:")
            for lesson in track_lessons:
                lesson_prefix = roman_number(int(lesson["order"]), uppercase=False)
                lesson_title = str(lesson["title"]).replace('"', "'")
                lines.extend(
                    [
                        f'            - text: "{lesson_prefix} {lesson_title}"',
                        f"              href: {lesson['source_path']}",
                    ]
                )
        else:
            lines.append("          contents: []")
    lines.extend(
        [
            '        - text: "Backgammon Glossary"',
            "          href: learn/glossary/index.qmd",
        ]
    )
    return "\n".join(lines) + "\n"


def build_lesson_catalogue_html(
    entries: list[dict[str, object]],
    curriculum: list[dict[str, object]],
    *,
    selected_track_id: str | None = None,
) -> str:
    selected_tracks = [
        track
        for track in curriculum
        if selected_track_id is None or track["id"] == selected_track_id
    ]
    if selected_track_id is not None and not selected_tracks:
        raise ValidationError(f"Unknown generated track {selected_track_id!r}")
    lessons = [
        lesson
        for track in selected_tracks
        for lesson in track["lessons"]  # type: ignore[union-attr]
    ]
    term_names = {str(entry["slug"]): str(entry["term"]) for entry in entries}
    used_difficulties = [
        value
        for value in DIFFICULTIES
        if any(value in lesson["categories"] for lesson in lessons)
    ]
    mode = "global" if selected_track_id is None else "track"
    lines = [
        GENERATED_MARKER,
        '<section class="bms-learn-filter-panel" data-bms-learn-filters '
        f'data-bms-learn-mode="{mode}" aria-label="Search and filter lessons">',
        '<div class="bms-learn-search-group">',
        '<label for="bms-learn-search">Search lessons</label>',
        '<input id="bms-learn-search" type="search" '
        'placeholder="Search titles and descriptions" '
        'autocomplete="off" data-bms-learn-search>',
        "</div>",
    ]
    lines.extend(
        filter_disclosure_html(
            "Difficulty Filter",
            "difficulty",
            [(value, value) for value in used_difficulties],
        )
    )
    if selected_track_id is None:
        lines.extend(
            filter_disclosure_html(
                "Learning Track Filter",
                "track",
                [
                    (str(track["id"]), str(track["title"]))
                    for track in curriculum
                ],
            )
        )
    else:
        used_term_slugs = sorted(
            {
                str(slug)
                for lesson in lessons
                for slug in lesson["terms"]
            },
            key=lambda slug: term_names[slug].casefold(),
        )
        lines.extend(
            filter_disclosure_html(
                "Term Filter",
                "term",
                [(slug, term_names[slug]) for slug in used_term_slugs],
            )
        )
    lines.extend(
        [
            '<div class="bms-learn-filter-footer">',
            '<p class="bms-learn-result-count" aria-live="polite" '
            "data-bms-learn-result-count></p>",
            '<button type="button" class="bms-learn-clear" '
            "data-bms-learn-clear hidden>Clear search and filters</button>",
            "</div>",
            "</section>",
            '<div class="bms-learn-section-actions" role="group" '
            'aria-label="Lesson tracks">',
            '<button type="button" data-bms-learn-collapse-all>Collapse all</button>',
            '<button type="button" data-bms-learn-expand-all>Expand all</button>',
            "</div>",
            '<div class="bms-learn-catalogue" data-bms-learn-list>',
        ]
    )

    for track in selected_tracks:
        track_lessons = track["lessons"]
        if not isinstance(track_lessons, list):
            raise ValidationError(f"Track {track['id']} has invalid lessons")
        track_title = str(track["title"])
        heading = (
            f'<span class="bms-learn-track-number" aria-hidden="true">'
            f'{roman_number(int(track["order"]))}</span>'
            f'<a href="{html_attr(track["route"])}">{html.escape(track_title)}</a>'
            if selected_track_id is None
            else '<span class="bms-learn-track-lessons-label">Lessons</span>'
        )
        lines.extend(
            [
                f'<details class="bms-learn-catalogue-section" '
                f'data-bms-learn-group data-bms-track-id="{html_attr(track["id"])}" '
                f'data-bms-total-lessons="{len(track_lessons)}" open>',
                '<summary class="bms-learn-catalogue-section-heading">',
                f'<span class="bms-learn-track-heading">{heading}</span>',
                f'<span data-bms-learn-group-count>{len(track_lessons)} '
                f'{"lesson" if len(track_lessons) == 1 else "lessons"}</span>',
                "</summary>",
                '<div class="bms-learn-catalogue-section-items">',
            ]
        )
        if track_lessons:
            for lesson in track_lessons:
                lines.extend(lesson_catalogue_item_html(lesson, term_names))
        else:
            lines.append(
                '<p class="bms-learn-track-empty">No lessons published yet.</p>'
            )
        lines.extend(["</div>", "</details>"])

    lines.extend(
        [
            "</div>",
            '<p class="bms-learn-empty" data-bms-learn-empty hidden>',
            "No lessons match this search and filter combination.",
            "</p>",
        ]
    )
    content = "\n".join(lines) + "\n"
    assert_no_forbidden_text(content, "generated Learn lesson catalogue")
    return content


def lesson_links_html(lessons: list[dict[str, object]], *, compact: bool = False) -> str:
    if not lessons:
        return ""
    item_lines = []
    for lesson in lessons:
        tracks = ", ".join(str(track) for track in lesson["tags"])
        suffix = f" <span>({html.escape(tracks)})</span>" if tracks and not compact else ""
        item_lines.append(
            f'<li><a href="{html_attr(lesson["route"])}">'
            f'{html.escape(str(lesson["title"]))}</a>{suffix}</li>'
        )
    return "\n".join(item_lines)


def research_links_html(articles: list[dict[str, object]]) -> str:
    item_lines = []
    for article in articles:
        description = str(article.get("description", "")).strip()
        description_html = (
            '<span class="bms-glossary-related-description">'
            f"{html.escape(description)}</span>"
            if description
            else ""
        )
        item_lines.append(
            f'<li><a href="{html_attr(article["route"])}">'
            f'{html.escape(str(article["title"]))}</a>{description_html}</li>'
        )
    return "\n".join(item_lines)


def related_sections_html(
    lessons: list[dict[str, object]],
    research_articles: list[dict[str, object]],
) -> list[str]:
    if not lessons and not research_articles:
        return []
    lines = ['<div class="bms-glossary-related-groups">']
    if lessons:
        lines.extend(
            [
                '<section class="bms-glossary-related bms-glossary-related--lessons">',
                f"<h4>Learn more ({len(lessons)})</h4>",
                "<ul>",
                lesson_links_html(lessons, compact=True),
                "</ul>",
                "</section>",
            ]
        )
    if research_articles:
        lines.extend(
            [
                '<section class="bms-glossary-related bms-glossary-related--research">',
                f"<h4>Research ({len(research_articles)})</h4>",
                "<ul>",
                research_links_html(research_articles),
                "</ul>",
                "</section>",
            ]
        )
    lines.append("</div>")
    return lines


def alias_html(aliases: list[dict[str, str]]) -> str:
    if not aliases:
        return ""
    alias_names = ", ".join(
        f'<span data-bms-alias="{html_attr(alias["slug"])}">'
        f'{html.escape(alias["term"])}</span>'
        for alias in aliases
    )
    return f'<p class="bms-glossary-aliases"><strong>Also called:</strong> {alias_names}</p>'


def usage_notes_html(entry: dict[str, object]) -> str:
    notes: list[str] = []
    if entry.get("usage_note"):
        notes.append(
            '<p class="bms-glossary-usage-note"><strong>Usage note:</strong> '
            f'{html.escape(str(entry["usage_note"]))}</p>'
        )
    for alias in entry["aliases"]:  # type: ignore[index]
        if alias.get("usage_note"):
            notes.append(
                '<p class="bms-glossary-usage-note"><strong>'
                f'{html.escape(str(alias["term"]))}:</strong> '
                f'{html.escape(str(alias["usage_note"]))}</p>'
            )
    return "\n".join(notes)


def build_entries_html(
    entries: list[dict[str, object]],
    related_lessons_by_slug: dict[str, list[dict[str, object]]],
    related_research_by_slug: dict[str, list[dict[str, object]]],
) -> str:
    groups: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in entries:
        groups[initial_group(str(entry["term"]))].append(entry)

    group_order = ["#"] + [chr(code) for code in range(ord("A"), ord("Z") + 1)]
    existing_groups = [group for group in group_order if group in groups]
    alphabet_links = " ".join(
        f'<a href="#letter-{html_attr("numbers" if group == "#" else group.lower())}" '
        f'data-bms-letter-link="{html_attr(group)}">'
        f"{html.escape(group)}</a>"
        for group in existing_groups
    )
    lines = [
        GENERATED_MARKER,
        '<nav class="bms-glossary-alphabet" aria-label="Glossary letters">',
        '<div class="bms-glossary-alphabet-links">',
        alphabet_links,
        "</div>",
        "</nav>",
        '<div class="bms-glossary-section-actions" role="group" '
        'aria-label="Glossary letter sections">',
        '<button type="button" class="bms-glossary-section-control" '
        'data-bms-glossary-collapse-all aria-controls="bms-glossary-groups">'
        "Collapse all</button>",
        '<button type="button" class="bms-glossary-section-control" '
        'data-bms-glossary-expand-all aria-controls="bms-glossary-groups" '
        "disabled>Expand all</button>",
        "</div>",
        '<div class="bms-glossary-groups" id="bms-glossary-groups" data-bms-glossary-groups>',
    ]

    for group in existing_groups:
        group_entries = groups[group]
        group_anchor = "numbers" if group == "#" else group.lower()
        lines.extend(
            [
                f'<details class="bms-glossary-letter-group" data-bms-letter-group open '
                f'id="letter-{html_attr(group_anchor)}" data-bms-letter="{html_attr(group)}">',
                f"<summary><span>{html.escape(group)}</span>"
                f'<span class="bms-glossary-letter-count">{len(group_entries)} terms</span>'
                "</summary>",
                '<div class="bms-glossary-letter-entries">',
            ]
        )
        for entry in group_entries:
            slug = str(entry["slug"])
            related_lessons = related_lessons_by_slug.get(slug, [])
            related_research = related_research_by_slug.get(slug, [])
            tracks = sorted(
                {
                    str(track)
                    for lesson in related_lessons
                    for track in lesson["tags"]
                },
                key=TRACKS.index,
            )
            search_values = [str(entry["term"])] + [
                str(alias["term"]) for alias in entry["aliases"]  # type: ignore[index]
            ]
            alias_slugs = [
                str(alias["slug"]) for alias in entry["aliases"]  # type: ignore[index]
            ]
            lines.extend(
                [
                    f'<details class="bms-glossary-entry" id="{html_attr(slug)}" '
                    f'data-bms-glossary-entry data-bms-slug="{html_attr(slug)}" '
                    f'data-bms-letter="{html_attr(group)}" '
                    f'data-bms-category="{html_attr(entry["category"])}" '
                    f'data-bms-tracks="{html_attr(json.dumps(tracks, ensure_ascii=False))}" '
                    f'data-bms-aliases="{html_attr(json.dumps(alias_slugs, ensure_ascii=False))}" '
                    f'data-bms-search="{html_attr(json.dumps(search_values, ensure_ascii=False))}">',
                    '<summary class="bms-glossary-entry-summary">'
                    f'<span class="bms-glossary-term-name">'
                    f'{html.escape(str(entry["term"]))}</span></summary>',
                    '<div class="bms-glossary-entry-body">',
                    alias_html(entry["aliases"]),  # type: ignore[arg-type]
                    f'<p class="bms-glossary-definition">{html.escape(str(entry["definition"]))}</p>',
                    f'<p class="bms-glossary-category"><strong>Category:</strong> '
                    f'<button type="button" data-bms-card-category="{html_attr(entry["category"])}">'
                    f'{html.escape(display_category(str(entry["category"])))}</button></p>',
                    usage_notes_html(entry),
                ]
            )
            lines.extend(related_sections_html(related_lessons, related_research))
            lines.extend(["</div>", "</details>"])
        lines.extend(["</div>", "</details>"])

    lines.append("</div>")
    content = "\n".join(line for line in lines if line != "") + "\n"
    assert_no_forbidden_text(content, "generated glossary index HTML")
    return content


def build_authoring_terms(entries: list[dict[str, object]]) -> str:
    lines = [
        "# Canonical Learn Glossary Terms",
        "",
        GENERATED_MARKER,
        "",
        "Use only these canonical slugs in Learn and Research `terms` metadata. "
        "Every term is defined on the one public glossary page; there are no "
        "standalone term routes.",
        "",
        "| Term | Canonical slug | Stable glossary anchor |",
        "|---|---|---|",
    ]
    for entry in entries:
        term = str(entry["term"]).replace("|", "\\|")
        slug = str(entry["slug"])
        lines.append(f"| {term} | `{slug}` | `/learn/glossary/#{slug}` |")
    content = "\n".join(lines) + "\n"
    assert_no_forbidden_text(content, "generated authoring term list")
    return content


def generated_outputs(
    entries: list[dict[str, object]],
    curriculum: list[dict[str, object]],
    related_lessons: dict[str, list[dict[str, object]]],
    related_research: dict[str, list[dict[str, object]]],
) -> dict[Path, str]:
    outputs = {
        GENERATED_LESSON_CATALOGUE_PATH: build_lesson_catalogue_html(
            entries, curriculum
        ),
        GENERATED_NAVIGATION_PATH: build_navigation_yaml(curriculum),
        GENERATED_ENTRIES_PATH: build_entries_html(
            entries, related_lessons, related_research
        ),
        AUTHORING_TERMS_PATH: build_authoring_terms(entries),
    }
    for track in curriculum:
        track_path = track["path"]
        if not isinstance(track_path, Path):
            raise ValidationError(f"Track {track['id']} has invalid path")
        outputs[track_path.parent / "_lesson-index.html"] = (
            build_lesson_catalogue_html(
                entries,
                curriculum,
                selected_track_id=str(track["id"]),
            )
        )
    return outputs


def remove_standalone_term_pages() -> list[Path]:
    removed: list[Path] = []
    expected_parent = GLOSSARY_ROOT.resolve()
    for source_path in sorted(GLOSSARY_ROOT.glob("*/index.qmd")):
        stale_path = source_path.resolve()
        if stale_path.parent.parent != expected_parent:
            raise ValidationError(f"Unsafe standalone glossary page: {stale_path}")
        content = stale_path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in content:
            raise ValidationError(
                f"Refusing to remove non-generated glossary page: {stale_path}"
            )
        stale_path.unlink()
        if not any(stale_path.parent.iterdir()):
            stale_path.parent.rmdir()
        removed.append(stale_path)
    if LEGACY_GENERATED_ROUTES_PATH.exists():
        LEGACY_GENERATED_ROUTES_PATH.unlink()
        removed.append(LEGACY_GENERATED_ROUTES_PATH)
    return removed


def generate() -> tuple[int, int, int]:
    data = read_json(PUBLIC_DATA_PATH)
    entries = validate_public_data(data)
    serialized = PUBLIC_DATA_PATH.read_text(encoding="utf-8")
    assert_no_forbidden_text(serialized, "tracked public glossary data")
    tracks = discover_tracks()
    lessons = discover_lessons()
    curriculum = build_curriculum(tracks, lessons)
    discover_cube_lessons()
    discover_update_publications()
    related_lessons = validate_lessons(lessons, entries)
    research_articles = discover_research_articles()
    related_research = validate_research_articles(research_articles, entries)

    outputs = generated_outputs(
        entries,
        curriculum,
        related_lessons,
        related_research,
    )
    removed = remove_standalone_term_pages()
    changed = sum(write_if_changed(path, content) for path, content in outputs.items())
    return changed, len(outputs), len(removed)


def validate_generated() -> dict[str, int]:
    data = read_json(PUBLIC_DATA_PATH)
    entries = validate_public_data(data)
    assert_no_forbidden_text(
        PUBLIC_DATA_PATH.read_text(encoding="utf-8"),
        "tracked public glossary data",
    )
    tracks = discover_tracks()
    lessons = discover_lessons()
    curriculum = build_curriculum(tracks, lessons)
    cube_lessons = discover_cube_lessons()
    update_publications = discover_update_publications()
    related_lessons = validate_lessons(lessons, entries)
    research_articles = discover_research_articles()
    related_research = validate_research_articles(research_articles, entries)
    expected = generated_outputs(
        entries,
        curriculum,
        related_lessons,
        related_research,
    )

    missing = [path for path in expected if not path.exists()]
    changed = [
        path
        for path, content in expected.items()
        if path.exists() and path.read_text(encoding="utf-8") != content
    ]
    if missing:
        raise ValidationError(
            "Missing generated files: "
            + ", ".join(str(path.relative_to(REPOSITORY_ROOT)) for path in missing[:10])
        )
    if changed:
        raise ValidationError(
            "Generated files are stale: "
            + ", ".join(str(path.relative_to(REPOSITORY_ROOT)) for path in changed[:10])
        )

    standalone_pages = sorted(GLOSSARY_ROOT.glob("*/index.qmd"))
    if standalone_pages:
        raise ValidationError(
            "Standalone glossary term pages remain: "
            + ", ".join(
                str(path.relative_to(REPOSITORY_ROOT))
                for path in standalone_pages[:10]
            )
        )
    if LEGACY_GENERATED_ROUTES_PATH.exists():
        raise ValidationError("Legacy glossary route manifest remains")

    canonical_slugs = {str(entry["slug"]) for entry in entries}
    entries_html = GENERATED_ENTRIES_PATH.read_text(encoding="utf-8")
    canonical_anchors = re.findall(
        r'<details class="bms-glossary-entry" id="([^"]+)"',
        entries_html,
    )
    if len(canonical_anchors) != len(entries) or set(canonical_anchors) != canonical_slugs:
        raise ValidationError("Single-page canonical anchors do not match glossary data")
    if len(canonical_anchors) != len(set(canonical_anchors)):
        raise ValidationError("Duplicate canonical glossary anchors")
    entry_tags = re.findall(
        r'<details class="bms-glossary-entry"[^>]*>',
        entries_html,
    )
    if any(" open" in tag for tag in entry_tags):
        raise ValidationError("Canonical term disclosures must begin collapsed")
    if entries_html.count('data-bms-alias="') != EXPECTED_ALIAS_ENTRIES:
        raise ValidationError("Generated alias count does not match public data")
    if entries_html.count('class="bms-glossary-definition"') != len(entries):
        raise ValidationError("Every canonical entry must include its full definition")
    old_term_links = [
        slug
        for slug in canonical_slugs
        if f'/learn/glossary/{slug}/' in entries_html
    ]
    if old_term_links:
        raise ValidationError(
            f"Single-page glossary still links to term routes: {old_term_links[:10]}"
        )

    catalogue_html = GENERATED_LESSON_CATALOGUE_PATH.read_text(encoding="utf-8")
    catalogue_items = re.findall(
        r'<article class="bms-learn-catalogue-item"[^>]*>',
        catalogue_html,
    )
    if len(catalogue_items) != len(lessons):
        raise ValidationError("Generated Learn catalogue has the wrong lesson count")
    if any(" open" in tag for tag in re.findall(
        r'<details class="bms-learn-catalogue-description"[^>]*>',
        catalogue_html,
    )):
        raise ValidationError("Lesson descriptions must begin collapsed")
    expected_routes = {str(lesson["route"]) for lesson in lessons}
    catalogue_routes = set(re.findall(
        r'<a class="bms-learn-catalogue-link" href="([^"]+)">',
        catalogue_html,
    ))
    if catalogue_routes != expected_routes:
        raise ValidationError("Generated Learn catalogue routes do not match lessons")
    catalogue_group_tags = re.findall(
        r'<details class="bms-learn-catalogue-section"[^>]*>',
        catalogue_html,
    )
    if len(catalogue_group_tags) != len(curriculum) or any(
        " open" not in tag for tag in catalogue_group_tags
    ):
        raise ValidationError(
            "Generated Learn track sections must all begin expanded"
        )
    for required in (
        "Difficulty Filter",
        "Learning Track Filter",
        "data-bms-learn-collapse-all",
        "data-bms-learn-expand-all",
    ):
        if required not in catalogue_html:
            raise ValidationError(
                f"Generated Learn catalogue is missing {required}"
            )

    for track in curriculum:
        track_path = track["path"]
        track_lessons = track["lessons"]
        if not isinstance(track_path, Path) or not isinstance(track_lessons, list):
            raise ValidationError(f"Track {track['id']} has invalid generated data")
        track_html = (track_path.parent / "_lesson-index.html").read_text(
            encoding="utf-8"
        )
        if track_html.count("data-bms-learn-item") != len(track_lessons):
            raise ValidationError(
                f"Generated track index {track['id']} has the wrong lesson count"
            )
        for required in (
            'data-bms-learn-mode="track"',
            "Difficulty Filter",
            "Term Filter",
            "data-bms-learn-collapse-all",
            "data-bms-learn-expand-all",
        ):
            if required not in track_html:
                raise ValidationError(
                    f"Generated track index {track['id']} is missing {required}"
                )
        if "data-bms-filter-track" in track_html:
            raise ValidationError(
                f"Generated track index {track['id']} contains a track filter"
            )
        track_group_tags = re.findall(
            r'<details class="bms-learn-catalogue-section"[^>]*>',
            track_html,
        )
        if len(track_group_tags) != 1 or " open" not in track_group_tags[0]:
            raise ValidationError(
                f"Generated track index {track['id']} must begin expanded"
            )
        track_description_tags = re.findall(
            r'<details class="bms-learn-catalogue-description"[^>]*>',
            track_html,
        )
        if len(track_description_tags) != len(track_lessons) or any(
            " open" in tag for tag in track_description_tags
        ):
            raise ValidationError(
                f"Generated track index {track['id']} descriptions must begin collapsed"
            )

    quarto_config = QUARTO_CONFIG_PATH.read_text(encoding="utf-8")
    if "metadata-files:" not in quarto_config or "_learn-navigation.yml" not in quarto_config:
        raise ValidationError(
            "Quarto configuration is missing the generated Learn navigation metadata"
        )

    related_lesson_count = sum(len(value) for value in related_lessons.values())
    related_research_count = sum(len(value) for value in related_research.values())
    return {
        "source_entries": EXPECTED_SOURCE_ENTRIES,
        "canonical_entries": len(entries),
        "alias_entries": sum(len(entry["aliases"]) for entry in entries),
        "lessons": len(lessons),
        "cube_lessons": len(cube_lessons),
        "updates_publications": len(update_publications),
        "research_articles": len(research_articles),
        "related_lesson_links": related_lesson_count,
        "related_research_links": related_research_count,
        "generated_files": len(expected),
        "lesson_catalogue_sections": len(curriculum),
        "learn_tracks": len(tracks),
        "canonical_anchors": len(canonical_anchors),
        "standalone_term_pages": 0,
    }


def validate_full_build_output(output_root: Path) -> None:
    marker = output_root / FULL_BUILD_MARKER_NAME
    if not marker.exists():
        raise ValidationError(
            "Rendered output is partial or has not completed a full site build: "
            f"missing {FULL_BUILD_MARKER_NAME}. Run a clean full Quarto build "
            "before complete-site validation."
        )
    try:
        marker_data = json.loads(marker.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as error:
        raise ValidationError(
            "Rendered full-build completion marker is unreadable or invalid"
        ) from error
    if marker_data != {
        "complete_full_build": True,
        "schema": FULL_BUILD_MARKER_SCHEMA,
    }:
        raise ValidationError(
            "Rendered full-build completion marker has an unsupported contract"
        )

    missing = [
        relative
        for relative in RENDERED_CORE_PATHS
        if not (output_root / relative).is_file()
    ]
    if missing:
        raise ValidationError(
            "Rendered site output is incomplete; required full-build pages are "
            "missing: " + ", ".join(missing)
        )


def validate_rendered_404(not_found_html: str) -> None:
    for text_value in (
        "Page closed out",
        "suspiciously bounced off the board",
    ):
        if text_value not in not_found_html:
            raise ValidationError(f"Rendered 404 is malformed: missing {text_value!r}")
    for route in NOT_FOUND_ROUTES:
        if f'href="{route}"' not in not_found_html:
            raise ValidationError(
                f"Rendered 404 links are malformed: missing clean link {route}"
            )
    if re.search(
        r'(http-equiv=["\']refresh|window\.location|location\.replace)',
        not_found_html,
        flags=re.IGNORECASE,
    ):
        raise ValidationError("Rendered 404 is malformed: contains redirect behavior")


def footer_rss_hrefs(page_html: str) -> list[str]:
    footer_match = re.search(
        r"<footer\b.*?</footer>",
        page_html,
        flags=re.DOTALL,
    )
    if not footer_match:
        return []
    return re.findall(
        r'href="([^"]*updates/index\.xml)"',
        footer_match.group(0),
    )


def validate_representative_rss_footers(output_root: Path) -> None:
    for relative in RSS_FOOTER_REPRESENTATIVE_PATHS:
        path = output_root / relative
        page_html = path.read_text(encoding="utf-8", errors="replace")
        hrefs = footer_rss_hrefs(page_html)
        if hrefs != ["/updates/index.xml"]:
            raise ValidationError(
                "Rendered footer RSS mismatch in "
                f"{relative}: expected ['/updates/index.xml'], found {hrefs}"
            )


def check_rendered(output_root: Path) -> dict[str, int]:
    validate_full_build_output(output_root)

    not_found_path = output_root / "404.html"
    if not not_found_path.exists():
        raise ValidationError("Rendered root 404.html is missing from the full build")
    not_found_html = not_found_path.read_text(encoding="utf-8", errors="replace")
    validate_rendered_404(not_found_html)

    updates_feed = output_root / "updates" / "index.xml"
    if not updates_feed.exists():
        raise ValidationError(
            "Rendered Updates RSS feed is missing: updates/index.xml"
        )

    sitemap = output_root / "sitemap.xml"
    if not sitemap.exists():
        raise ValidationError("Rendered sitemap.xml is missing from the full build")

    glossary_output = output_root / "learn" / "glossary"
    glossary_index = glossary_output / "index.html"
    if not glossary_index.exists():
        raise ValidationError(f"Rendered glossary output is missing: {glossary_index}")

    html_files = sorted(glossary_output.rglob("*.html"))
    if html_files != [glossary_index]:
        raise ValidationError(
            "Rendered glossary must contain exactly one HTML page; found "
            + ", ".join(str(path.relative_to(output_root)) for path in html_files[:10])
        )

    data = read_json(PUBLIC_DATA_PATH)
    entries = validate_public_data(data)
    canonical_slugs = {str(entry["slug"]) for entry in entries}
    alias_count = sum(len(entry["aliases"]) for entry in entries)
    glossary_html = glossary_index.read_text(encoding="utf-8", errors="replace")
    assert_no_forbidden_text(glossary_html, "rendered single-page glossary")

    canonical_anchors = re.findall(
        r'<details class="bms-glossary-entry" id="([^"]+)"',
        glossary_html,
    )
    if len(canonical_anchors) != len(entries) or set(canonical_anchors) != canonical_slugs:
        raise ValidationError("Rendered canonical anchors do not match glossary data")
    if len(canonical_anchors) != len(set(canonical_anchors)):
        raise ValidationError("Rendered glossary contains duplicate canonical anchors")

    entry_tags = re.findall(
        r'<details class="bms-glossary-entry"[^>]*>',
        glossary_html,
    )
    if any(" open" in tag for tag in entry_tags):
        raise ValidationError("Rendered term disclosures do not begin collapsed")
    if glossary_html.count('class="bms-glossary-definition"') != len(entries):
        raise ValidationError("Rendered glossary is missing full definitions")
    if glossary_html.count('data-bms-alias="') != alias_count:
        raise ValidationError("Rendered glossary alias count is incorrect")
    if any(f"/learn/glossary/{slug}/" in glossary_html for slug in canonical_slugs):
        raise ValidationError("Rendered glossary still links to standalone term routes")

    tracks = discover_tracks()
    lessons = discover_lessons()
    curriculum = build_curriculum(tracks, lessons)
    learn_index = output_root / "learn" / "index.html"
    learn_html = learn_index.read_text(encoding="utf-8", errors="replace")
    if learn_html.count("data-bms-learn-item") != len(lessons):
        raise ValidationError("Rendered Learn catalogue has the wrong lesson count")
    for required in (
        "data-bms-learn-search",
        "data-bms-filter-difficulty",
        "data-bms-filter-track",
        "data-bms-learn-group",
        "data-bms-learn-clear",
        "data-bms-learn-empty",
        "data-bms-learn-collapse-all",
        "data-bms-learn-expand-all",
    ):
        if required not in learn_html:
            raise ValidationError(f"Rendered Learn catalogue is missing {required}")
    rendered_catalogue_routes = {
        urljoin(
            "/learn/",
            html.unescape(href),
        )
        for href in re.findall(
            r'<a class="bms-learn-catalogue-link" href="([^"]+)">',
            learn_html,
        )
    }
    expected_catalogue_routes = {str(lesson["route"]) for lesson in lessons}
    if rendered_catalogue_routes != expected_catalogue_routes:
        raise ValidationError(
            "Rendered Learn catalogue routes do not match lesson routes"
        )
    description_tags = re.findall(
        r'<details class="bms-learn-catalogue-description"[^>]*>',
        learn_html,
    )
    if len(description_tags) != len(lessons) or any(
        " open" in tag for tag in description_tags
    ):
        raise ValidationError(
            "Rendered Learn lesson descriptions must all begin collapsed"
        )
    catalogue_group_tags = re.findall(
        r'<details class="bms-learn-catalogue-section"[^>]*>',
        learn_html,
    )
    if len(catalogue_group_tags) != len(curriculum) or any(
        " open" not in tag for tag in catalogue_group_tags
    ):
        raise ValidationError(
            "Rendered Learn track sections must all begin expanded"
        )
    for track in curriculum:
        numbered_title = (
            f"{roman_number(int(track['order']))} {str(track['title'])}"
        )
        if html.escape(numbered_title) not in learn_html:
            raise ValidationError(
                f"Rendered Learn catalogue is missing track heading {numbered_title!r}"
            )
    obsolete_finder = output_root / "learn" / "lesson-finder" / "index.html"
    if obsolete_finder.exists():
        raise ValidationError(
            "Rendered output is stale: the removed Lesson Finder page remains"
        )

    letter_tags = re.findall(
        r'<details class="bms-glossary-letter-group"[^>]*>',
        glossary_html,
    )
    if not letter_tags or any(" open" not in tag for tag in letter_tags):
        raise ValidationError("Rendered glossary letter sections must begin expanded")
    if (
        glossary_html.count("data-bms-glossary-collapse-all") != 1
        or glossary_html.count("data-bms-glossary-expand-all") != 1
    ):
        raise ValidationError("Rendered glossary is missing the two letter controls")

    sitemap_text = sitemap.read_text(encoding="utf-8", errors="replace")
    if "/learn/lesson-finder/" in sitemap_text:
        raise ValidationError("Sitemap still contains the removed Lesson Finder route")
    glossary_locations = [
        html.unescape(location)
        for location in re.findall(r"<loc>(.*?)</loc>", sitemap_text)
        if "/learn/glossary/" in location
    ]
    expected_glossary_location = (
        "https://backgammon-made-simple.github.io/learn/glossary/"
    )
    if glossary_locations != [expected_glossary_location]:
        raise ValidationError(
            f"Sitemap glossary locations are incorrect: {glossary_locations[:10]}"
        )

    canonical = (
        '<link rel="canonical" '
        'href="https://backgammon-made-simple.github.io/learn/glossary/">'
    )
    if canonical not in glossary_html:
        raise ValidationError("Rendered glossary is missing its one canonical URL")
    shared_image = (
        "https://backgammon-made-simple.github.io/"
        "assets/social/generated/social-glossary.png"
    )
    if shared_image not in glossary_html:
        raise ValidationError("Rendered glossary is missing its shared social image")

    lesson_path = (
        output_root
        / "learn"
        / "cube"
        / "why-is-25-percent-the-basic-take-point.html"
    )
    research_path = (
        output_root / "research" / "sage-vs-gnu-additional-details.html"
    )
    for label, path in (
        ("Learn lesson", lesson_path),
        ("Research article", research_path),
    ):
        if not path.exists():
            raise ValidationError(f"Rendered {label} is missing: {path}")
        page_html = path.read_text(encoding="utf-8", errors="replace")
        if 'id="TOC"' not in page_html or 'data-toc-expanded="99"' not in page_html:
            raise ValidationError(f"Rendered {label} is missing native expanded TOC")
        if "bms-research-toc-toggle" in page_html:
            raise ValidationError(f"Rendered {label} contains a competing TOC initializer")

    for track in curriculum:
        route = str(track["route"])
        track_index = output_root / route.strip("/") / "index.html"
        if not track_index.exists():
            raise ValidationError(
                f"Rendered track index {track['id']} is missing: {track_index}"
            )
        track_html = track_index.read_text(encoding="utf-8", errors="replace")
        track_lessons = track["lessons"]
        if not isinstance(track_lessons, list):
            raise ValidationError(f"Track {track['id']} has invalid lessons")
        if track_html.count("data-bms-learn-item") != len(track_lessons):
            raise ValidationError(
                f"Rendered track index {track['id']} has the wrong lesson count"
            )
        for required in (
            'data-bms-learn-mode="track"',
            "Difficulty Filter",
            "Term Filter",
            "data-bms-learn-collapse-all",
            "data-bms-learn-expand-all",
            "data-bms-learn-clear",
            "data-bms-learn-empty",
        ):
            if required not in track_html:
                raise ValidationError(
                    f"Rendered track index {track['id']} is missing {required}"
                )
        if "data-bms-filter-track" in track_html:
            raise ValidationError(
                f"Rendered track index {track['id']} contains a track filter"
            )
        if "data-bms-term-lookup" in track_html:
            raise ValidationError(
                f"Rendered track index {track['id']} contains the term lookup"
            )
        track_group_tags = re.findall(
            r'<details class="bms-learn-catalogue-section"[^>]*>',
            track_html,
        )
        if len(track_group_tags) != 1 or " open" not in track_group_tags[0]:
            raise ValidationError(
                f"Rendered track index {track['id']} must begin expanded"
            )
        track_description_tags = re.findall(
            r'<details class="bms-learn-catalogue-description"[^>]*>',
            track_html,
        )
        if len(track_description_tags) != len(track_lessons) or any(
            " open" in tag for tag in track_description_tags
        ):
            raise ValidationError(
                f"Rendered track index {track['id']} descriptions must begin collapsed"
            )
        title_positions = [
            track_html.find(html.escape(str(lesson["title"])))
            for lesson in track_lessons
        ]
        if any(position < 0 for position in title_positions) or title_positions != sorted(
            title_positions
        ):
            raise ValidationError(
                f"Rendered track index {track['id']} lessons are missing or out of order"
            )
    validate_representative_rss_footers(output_root)
    try:
        feed_root = ElementTree.parse(updates_feed).getroot()
    except ElementTree.ParseError as error:
        raise ValidationError("Rendered combined Updates RSS feed is invalid XML") from error
    feed_items = feed_root.findall("./channel/item")
    feed_links = [
        (item.findtext("link") or "").strip()
        for item in feed_items
    ]
    expected_feed_links = [
        "https://backgammon-made-simple.github.io" + str(publication["route"])
        for publication in discover_update_publications()
    ]
    if feed_links != expected_feed_links:
        raise ValidationError(
            "Rendered Updates RSS items are missing, ineligible, or out of order"
        )
    if any(
        re.match(r"^\s*\d+\.\s+", item.findtext("title") or "")
        for item in feed_items
    ):
        raise ValidationError("Cube landing numbers leaked into an RSS title")

    return {
        "alias_entries": alias_count,
        "canonical_anchors": len(canonical_anchors),
        "glossary_html_files": len(html_files),
        "sitemap_glossary_routes": len(glossary_locations),
        "standalone_term_pages": 0,
        "updates_feed_items": len(feed_items),
    }

def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command")

    import_parser = subparsers.add_parser(
        "import-public-safe", help="Import the authorized public-safe bundle"
    )
    import_parser.add_argument("--input", required=True, type=Path)

    subparsers.add_parser("generate", help="Regenerate glossary sources")
    subparsers.add_parser("validate", help="Validate data, metadata, and generated sources")

    rendered_parser = subparsers.add_parser(
        "check-rendered", help="Check rendered glossary HTML and sitemap"
    )
    rendered_parser.add_argument("--output", type=Path, default=SITE_ROOT / "_site")

    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    command = args.command or "generate"
    try:
        if command == "import-public-safe":
            data = import_public_safe(args.input.resolve())
            print(
                f"Imported {len(data['entries'])} canonical entries to "
                f"{PUBLIC_DATA_PATH.relative_to(REPOSITORY_ROOT)}"
            )
            return 0
        if command == "generate":
            changed, total, removed = generate()
            print(
                "Glossary generation complete: "
                f"{changed} changed, {total} checked, {removed} obsolete files removed"
            )
            return 0
        if command == "validate":
            result = validate_generated()
            print("Glossary validation passed: " + json.dumps(result, sort_keys=True))
            return 0
        if command == "check-rendered":
            result = check_rendered(args.output.resolve())
            print("Rendered glossary check passed: " + json.dumps(result, sort_keys=True))
            return 0
    except (OSError, json.JSONDecodeError, ValidationError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    raise AssertionError(f"Unhandled command: {command}")


if __name__ == "__main__":
    raise SystemExit(main())
